joist-orm/joist-orm

packages/codegen/src/EntityDbMetadata.ts

Joist doesn't know what to do with a FK on multiple columns, so filter them out.

Filter out foreign keys on multiple columns

---

docs/misc-features.markdown
packages/codegen/src/generateEntityCodegenFile.ts
packages/codegen/src/symbols.ts
packages/integration-tests/src/collections/hasOneDerived.test.ts
packages/integration-tests/src/entities/AuthorCodegen.ts
packages/integration-tests/src/entities/BookCodegen.ts
packages/integration-tests/src/entities/BookReview.ts
packages/integration-tests/src/entities/BookReviewCodegen.ts
packages/integration-tests/src/entities/Image.ts
packages/integration-tests/src/entities/ImageCodegen.ts
packages/integration-tests/src/entities/PublisherCodegen.ts
packages/integration-tests/src/entities/TagCodegen.ts
packages/orm/src/EntityManager.ts
packages/orm/src/collections/CustomReference.ts
packages/orm/src/collections/ManyToManyCollection.ts
packages/orm/src/collections/ManyToOneReference.ts
packages/orm/src/collections/hasOneDerived.ts
packages/orm/src/collections/hasOneThrough.ts
packages/orm/src/collections/index.ts
packages/orm/src/index.ts

Needed this for commitment line items having a commitment that is either the change order or the commitment.

Add hasOneDerived.

---

packages/codegen/src/EntityDbMetadata.ts
packages/codegen/src/generateEntityCodegenFile.ts
packages/codegen/src/generateMetadataFile.ts
packages/integration-tests/src/EntityManager.unsafe.test.ts
packages/integration-tests/src/entities/AuthorCodegen.ts
packages/integration-tests/src/entities/BookAdvanceCodegen.ts
packages/integration-tests/src/entities/BookCodegen.ts
packages/integration-tests/src/entities/BookReviewCodegen.ts
packages/integration-tests/src/entities/ImageCodegen.ts
packages/integration-tests/src/entities/PublisherCodegen.ts
packages/integration-tests/src/entities/TagCodegen.ts
packages/integration-tests/src/entities/metadata.ts
packages/orm/src/EntityManager.ts
packages/orm/src/createOrUpdatePartial.ts

So we can stop mapping id keys all the time.

Support passing bookId/bookIds keys to partials.

---

packages/integration-tests/src/EntityManager.queries.test.ts
packages/orm/src/QueryBuilder.ts

You could say,  `ILIKE` this idea a lot.

Add support for ILIKE operator

---

packages/integration-tests/src/reverseHint.test.ts
packages/orm/src/reverseHint.ts

Allow reverseHint to work for o2o relationships

allow reverseHints for o2o

---

packages/integration-tests/src/EntityManager.unsafe.test.ts
packages/integration-tests/src/collections/ManyToManyCollection.test.ts
packages/orm/src/createOrUpdatePartial.ts
packages/orm/src/index.ts

This fixes wonkiness around "I think I'm exhaustively setting a
colection but I'm not really".
Granted, historically we might have relied upon this as a feature,
although AFAIU what's more likely is that we specifically wanted
to control child entity lifecycle via commands like `delete: true`
and less that we wanted incremental collections specifically.
(I.e. all of our parent + line items mutations, which are our most common
usage of this pattern, post exhaustive collections of the child line items.)
(Also, IMO it's likely that updating collections incrementally was also
convenient b/c the `.add` and `.remove` calls "work" without being
loaded, and `setOpts` is synchronous, so I'm tempted to think this was
also out of convenience than raw need.)
(Separately, ManyToManyCollection.add is …

Use Collection.set in setOpts even with partial=true.

---

packages/orm/src/newTestInstance.ts

It confuses factories that want to purposefully fan out, i.e. markets always creating their own product attributes, and internal users always creating their own user.

Don't pass implicit use entities as opts.

---

packages/integration-tests/src/EntityManager.lens.test.ts
packages/orm/src/loadLens.ts

I was working with some `.load`s and ending up with types like `Publisher[] | undefined[]` which made `filter` get confused.
I had an initial version of this that fixed the type to be `(Publisher | undefined)[]` which at least let `filter(isDefined)` work, but after thinking about, I think just dropping `undefined` directly in the method will basically always be what we want to happen (once we're in `flatMap` mode i.e. navigation through a known collection).

Filter undefineds out of lens navigation.

---

docs/docs/features/tagged-ids.md
packages/integration-tests/src/taggedIds.test.ts
packages/orm/src/EntityManager.ts
packages/orm/src/keys.ts
packages/orm/src/newTestInstance.ts

Also add overloads for `EntityConstructor`s and `number`s.

fix: Rename tagIfNeeded to just tagId.

---

packages/codegen/src/generateInitialEntityFile.ts
packages/integration-tests/src/entities/Critic.ts
packages/orm/src/config.ts

feat: Add config.placeholder to initial entity files.

---

packages/integration-tests/src/entities/Author.test.ts
packages/orm/src/changes.ts

feat: Add changes.originalEntity for m2o fields.

---

packages/codegen/src/EntityDbMetadata.ts
packages/codegen/src/generateEntityCodegenFile.ts
packages/graphql-codegen/src/generateGraphqlSchemaFiles.test.ts
packages/integration-tests/migrations/1580658856631_author.ts
packages/integration-tests/src/EntityManager.factories.test.ts
packages/integration-tests/src/entities/AuthorCodegen.ts
packages/integration-tests/src/entities/Book.test.ts
packages/integration-tests/src/entities/BookAdvanceCodegen.ts
packages/integration-tests/src/entities/BookCodegen.ts
packages/integration-tests/src/entities/BookReviewCodegen.ts
packages/integration-tests/src/entities/CommentCodegen.ts
packages/integration-tests/src/entities/CriticCodegen.ts
packages/integration-tests/src/entities/CriticColumnCodegen.ts
packages/integration-tests/src/entities/ImageCodegen.ts
packages/integration-tests/src/entities/Publisher.test.ts
packages/integration-tests/src/entities/PublisherCodegen.ts
packages/integration-tests/src/entities/TagCodegen.ts
packages/integration-tests/src/entities/metadata.ts
packages/orm/src/newTestInstance.ts
packages/tests/uuid-ids/src/entities/AuthorCodegen.ts
packages/tests/uuid-ids/src/entities/BookCodegen.ts
packages/tests/uuid-ids/src/entities/entities.ts
packages/tests/uuid-ids/src/entities/metadata.ts

fix: Teach factories about default values.

---

release.config.js

Update the command to correctly publish to npm.

fix: Correct semantic release publishCmd

---

packages/orm/src/EntityManager.ts

Because it's both likely to break and b/c we shouldn't really need
to anyway.

fix: Skip recursing into custom relations.

---

packages/integration-tests/src/EntityManager.test.ts
packages/orm/src/BaseEntity.ts

fix: Make BaseEntity.toJSON more Prisma-like.

---

packages/integration-tests/src/EntityManager.test.ts
packages/orm/src/EntityManager.ts
packages/orm/src/changes.ts

Also add updatedAt/createdAt handling.

fix: Fix hasChanged on cloned fields that are unset.

---

packages/orm/src/drivers/PostgresDriver.ts
packages/tests/schema-misc/src/entities/Author.test.ts
packages/tests/schema-misc/src/entities/Book.test.ts

fix: Quote table names.

---

.prettierrc.js
packages/integration-tests/src/EntityManager.test.ts
packages/orm/src/EntityManager.ts

fix: Fix cloning polymorphic references.

---

.circleci/config.yml
docs/docs/getting-started/configuration.md
packages/codegen/src/config.ts
packages/codegen/src/index.ts
packages/integration-tests/package.json
packages/tests/schema-misc/joist-codegen.json
packages/tests/schema-misc/local.env
packages/tests/schema-misc/package.json
packages/tests/schema-misc/run.sh

feat: Add databaseUrl to joist-codegen

---

packages/integration-tests/src/EntityManager.factories.test.ts
packages/integration-tests/src/entities/Author.test.ts
packages/orm/src/newTestInstance.ts
packages/orm/src/relations/hasPersistedAsyncProperty.ts

Fixes #371 which was for AsyncProperties and already fixed.

fix: Fix PersistedAsyncProperties in DeepNew.

---

packages/integration-tests/src/EntityManager.test.ts
packages/integration-tests/src/entities/Author.ts
packages/orm/src/EntityManager.ts
packages/orm/src/config.ts
packages/orm/src/rules.ts

feat: Support pretty-but-hard-coded messages for constraint failures.

---

packages/integration-tests/src/relations/OneToManyCollection.test.ts
packages/test-utils/src/toMatchEntity.ts

The recent fix of "finding m2os pointing to an id before the instance was loaded" also picked up _deleted_ entities.
Which is technically fine b/c `.get` filters both hard and soft deleted.
But it was a breaking change to `toMatchEntity`, which wanted to be helpful and include soft-deleted entities in its assertions, but was also picking up hard-deleted, which we do actually want to ignore.

fix: Fix hard deletes showing up in toMatchEntity.

---

packages/integration-tests/src/entities/Author.test.ts
packages/orm/src/changes.ts

Also fix an originalValue of undefined should not get stomped.

fix: Fix originalValue sometimes returning an entity.

---

packages/integration-tests/src/EntityManager.queries.test.ts
packages/integration-tests/src/EntityManager.test.ts
packages/orm/src/QueryBuilder.ts
packages/orm/src/QueryParser.ts

Otherwise the number of columns across the UNION ALLs changes.

fix: Fix batching order bys shouldn't distinct.

---

packages/orm/src/Aliases.ts

Hey @stephenh, I was trying your latest change for aliases but I'm getting an error when trying to run the codegen.
Already tried this change locally and now the codegen passes.

fix: utils import

---

packages/integration-tests/src/EntityManager.lens.test.ts
packages/orm/src/dataloaders/lensDataLoader.ts
packages/orm/src/dataloaders/oneToManyDataLoader.ts

fix: Wrap aliases that might be keywords.

---

docs/docs/getting-started/configuration.md
packages/codegen/src/config.ts
packages/codegen/src/index.ts
packages/utils/src/connection.ts

feat: Support creating `flush_database` in multiple databases.

---

packages/orm/src/keys.ts
packages/orm/src/relations/ManyToOneReference.ts
packages/tests/untagged-ids/src/entities/Author.test.ts

fix: Fix m2o.id can return untagged ids.

---

packages/orm/src/EntityManager.ts
packages/orm/src/dataloaders/findByUniqueDataLoader.ts
packages/orm/src/dataloaders/findDataLoader.ts
packages/orm/src/dataloaders/lensDataLoader.ts
packages/orm/src/dataloaders/loadDataLoader.ts
packages/orm/src/dataloaders/manyToManyDataLoader.ts
packages/orm/src/dataloaders/manyToManyFindDataLoader.ts
packages/orm/src/dataloaders/oneToManyDataLoader.ts
packages/orm/src/dataloaders/oneToManyFindDataLoader.ts
packages/orm/src/dataloaders/oneToOneDataLoader.ts

Really a chore, but marking as a feature to trigger a release.

feat: Refactor get loader

---

packages/integration-tests/src/EntityManager.find.batch.test.ts
packages/integration-tests/src/EntityManager.queries.test.ts
packages/orm/src/EntityFilter.ts
packages/orm/src/EntityGraphQLFilter.ts
packages/orm/src/QueryParser.ts
packages/orm/src/dataloaders/findDataLoader.ts
packages/orm/src/drivers/buildKnexQuery.ts

feat: Add more array operators.

---

packages/integration-tests/src/EntityManager.queries.test.ts
packages/orm/src/Aliases.ts

fix: Allow primitive conditions to do is/is not null.

---

packages/integration-tests/src/EntityManager.test.ts
packages/orm/src/EntityManager.ts

fix: ignore PersistedAsyncReference on em refresh

---

packages/integration-tests/src/EntityManager.find.batch.test.ts
packages/orm/src/QueryParser.ts
packages/orm/src/dataloaders/findDataLoader.ts

fix: Fix join order in batch finds.

---

packages/integration-tests/src/EntityManager.find.batch.test.ts
packages/orm/src/dataloaders/findDataLoader.ts

fix: Fix multiple nested conditions.

---

docs/docs/modeling/derived-fields.md

Adding docs for async derived fields

fix(docs): More docs for async derived fields

---

packages/integration-tests/src/entities/Author.ts
packages/integration-tests/src/entities/Book.ts
packages/orm/src/BaseEntity.ts
packages/orm/src/reactiveHints.ts

To highlight it's non-reactive-ness.

feat: Rename entity to fullNonReactiveAccess.

---

packages/codegen/src/config.ts
packages/codegen/src/index.ts

feat: Output warnings for stale/invalid config keys.

---

docs/docs/modeling/relations.md

Docs: Adding to the many to many requirements in the docs.

docs: Adding many to many requirement to docs

---

README.markdown
docs/docs/goals/overview.md
docs/docusaurus.config.js
docs/src/pages/index.tsx

docs: Move to discord.

---

packages/integration-tests/src/Entity.test.ts
packages/integration-tests/src/entities/Author.ts
packages/integration-tests/src/relations/hasAsyncMethod.test.ts
packages/orm/src/loadHints.ts
packages/orm/src/relations/hasAsyncMethod.ts
packages/orm/src/relations/index.ts

feat: Add async method

---

packages/integration-tests/src/EntityManager.test.ts
packages/orm/src/dataloaders/findOrCreateDataLoader.ts

Previously multiple `findOrCreate`s with the same `where` but different `ifNew`/`upsert` values were correctly getting batched into the same `load(keys)` call, but we were still em.creating an entity for each different ifNew/upsert clause.
Instead the intent was to just pick an arbitrary upsert clause as a winner, which this PR actually does.
We could potentially also fail here, and let the user know they're asking for the same entity to be set to different values; maybe as an opt to findOrCreate.

fix: Avoid creating dups if different upsert clauses.

---

packages/integration-tests/src/relations/ManyToManyCollection.test.ts
packages/orm/src/JoinRows.ts

Only happened if a m2m row was added/removed/added/removed 3x. :-|

fix: Fix m2m add/remove bug.

---

packages/integration-tests/src/EntityManager.assignNewIds.test.ts
packages/orm/src/EntityManager.ts

If batching is desired, this might be a solution.

feat: batch assignNewIds

---

packages/integration-tests/src/EntityManager.createOrUpdatePartial.test.ts
packages/integration-tests/src/entities/Author.ts
packages/integration-tests/src/getProperties.test.ts
packages/orm/src/createOrUpdatePartial.ts
packages/orm/src/getProperties.ts
packages/orm/src/index.ts

I don't have support in the types yet, but pushing this out as WIP.

feat: Allow non-field properties in createOrUpdatePartial.

---

packages/integration-tests/src/relations/hasAsyncMethod.test.ts
packages/orm/src/relations/hasAsyncMethod.ts

To highlight it can have side effects.

feat: Rename AsyncMethod.get to call.

---

packages/codegen/src/generate.ts
packages/codegen/src/generateEntityCodegenFile.ts
packages/orm/src/EntityManager.ts
packages/tests/integration/src/entities/metadata.ts
packages/tests/number-ids/src/entities/metadata.ts
packages/tests/schema-misc/src/entities/metadata.ts
packages/tests/untagged-ids/src/entities/metadata.ts
packages/tests/uuid-ids/src/entities/metadata.ts

Revert "feat: Generate an app-specific Entity type."

---

.idea/jsonSchemas.xml
packages/codegen/config-json-schema.json
packages/codegen/package.json
packages/codegen/src/EntityDbMetadata.test.ts
packages/codegen/src/config.test.ts
packages/codegen/src/config.ts
packages/codegen/src/generate.ts
packages/codegen/src/write-json-schema.ts
yarn.lock

feat: Add a Zod/json-schema config for joist-config.json file

---

packages/orm/src/relations/hasAsyncMethod.ts
packages/tests/integration/src/relations/hasAsyncMethod.test.ts

Fixing a silly typo from the last PR, with a regression test.

fix: Fix async methods that have load called twice.

---

packages/orm/src/drivers/PostgresDriver.ts
packages/tests/integration/src/EntityManager.large.test.ts

Uses the same code we did for batch inserts, but for updates.
Fixes #415

feat: Batch updates.

---

packages/orm/src/relations/OneToManyCollection.ts
packages/tests/integration/src/Inheritance.test.ts
packages/tests/integration/src/entities/Publisher.ts

fix: Fix cascade deletes declared in base classes.

---

packages/codegen/src/generateMetadataFile.ts
packages/orm/src/EntityMetadata.ts
packages/orm/src/dataloaders/findOrCreateDataLoader.ts
packages/tests/integration/migrations/1580658856631_author.ts
packages/tests/integration/src/EntityManager.queries.test.ts
packages/tests/integration/src/EntityManager.test.ts
packages/tests/integration/src/entities/metadata.ts

feat: Add citext support to findOrCreate.

---

packages/orm/src/config.ts
packages/orm/src/index.ts

feat: Ensure that rules/hooks aren't added post-boot.

---

packages/orm/src/QueryParser.ts
packages/tests/integration/joist-config.json
packages/tests/number-ids/joist-config.json
packages/tests/schema-misc/joist-config.json
packages/tests/untagged-ids/joist-config.json
packages/tests/untagged-ids/migrations/1580658856631_author.ts
packages/tests/untagged-ids/src/entities/AuthorCodegen.ts
packages/tests/untagged-ids/src/entities/BookCodegen.ts
packages/tests/untagged-ids/src/entities/Comment.factories.ts
packages/tests/untagged-ids/src/entities/Comment.ts
packages/tests/untagged-ids/src/entities/CommentCodegen.ts
packages/tests/untagged-ids/src/entities/PolymorphicField.untagged.test.ts
packages/tests/untagged-ids/src/entities/entities.ts
packages/tests/untagged-ids/src/entities/factories.ts
packages/tests/untagged-ids/src/entities/metadata.ts
packages/tests/uuid-ids/joist-config.json

The entity still must know its tagged id, we just make sure to go through idTaggedMaybe instead of just idMaybe.

fix: Fix em.find on poly with untagged ids.

---

packages/codegen/src/symbols.ts
packages/orm/src/index.ts
packages/tests/integration/src/entities/Author.ts
packages/tests/integration/src/entities/Publisher.ts

Intead every entity has an `em` field.

fix: Remove legacy getEm method.

---

docs/docs/goals/avoiding-n-plus-1s.md

Hi, just fixing some typos I noticed while reading this page. Thanks for writing a great general overview on N+1s and how Joist specifically addresses them!

docs: Fix a few copy issues in avoiding-n-plus-1s.md

---

packages/tests/integration/src/relations/ReactiveField.test.ts

Just updating some of the old "persisted derived field" language, plus misc re-org.

chore: Update test names.

---

packages/orm/src/config.ts

And allow the hot reloads to re-boot the config rules.

fix: Detect running in NextJS.

---

packages/plugins/join-preloading/package.json
yarn.lock

fix: Plugins should use a peer dependency.

---

docs/docs/features/queries-find.md
packages/orm/src/EntityManager.ts
packages/orm/src/dataloaders/findOrCreateDataLoader.ts
packages/tests/integration/src/EntityManager.test.ts

feat: Add findWithNewOrChanged.

---

packages/orm/src/loadLens.ts

In one of our GraphQL responses that is traversing ~10k lenses, this reduced local response time from ~800ms to ~550ms or about a 25% savings.
This response was admittedly doing a ~pathological amount of lens traversals, but still a good win.

fix: Optimize loadLens to not rely on exceptions.

---

packages/orm/src/newTestInstance.ts
packages/tests/integration/src/EntityManager.factories.test.ts

fix: Allow skipping useExisting.

---

docs/docs/testing/test-factories.md
packages/orm/package.json
packages/orm/src/index.ts
packages/orm/src/newTestInstance.ts
packages/test-utils/src/toMatchEntity.ts
packages/tests/esm-misc/joist-config.json
packages/tests/immediate-foreign-keys/joist-config.json
packages/tests/integration/joist-config.json
packages/tests/integration/src/EntityManager.factories.test.ts
packages/tests/integration/src/EntityManager.find.batch.test.ts
packages/tests/integration/src/EntityManager.joins.test.ts
packages/tests/integration/src/EntityManager.queries.test.ts
packages/tests/integration/src/EntityManager.softDeletes.test.ts
packages/tests/integration/src/EntityManager.test.ts
packages/tests/integration/src/Inheritance.test.ts
packages/tests/integration/src/entities/Author.test.ts
packages/tests/integration/src/testDates.ts
packages/tests/integration/src/toMatchEntity.test.ts
packages/tests/number-ids/joist-config.json
packages/tests/schema-misc/joist-config.json
packages/tests/temporal/joist-config.json
packages/tests/untagged-ids/joist-config.json
packages/tests/uuid-ids/joist-config.json
yarn.lock

If you pass `useLogging: true` to a factory call, we get "tell me wtf is going on" console output:

feat: Add factory logging

---

packages/codegen/src/codemods/index.ts
packages/orm/src/reactiveHints.ts
packages/tests/esm-misc/joist-config.json
packages/tests/immediate-foreign-keys/joist-config.json
packages/tests/integration/joist-config.json
packages/tests/integration/src/relations/ReactiveReference.test.ts
packages/tests/number-ids/joist-config.json
packages/tests/schema-misc/joist-config.json
packages/tests/temporal/joist-config.json
packages/tests/untagged-ids/joist-config.json
packages/tests/uuid-ids/joist-config.json

commit-id:4497cfee
---
**Stack**:
- #1127 ⬅
- #1126
- #1125
- #1124
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

chore: Rename ReactiveReference.test.ts.

---

packages/orm/src/relations/OneToOneReference.ts
packages/orm/src/relations/ReactiveReference.ts
packages/tests/integration/src/relations/ReactiveReference.test.ts

fix: Avoid calling ReactiveReference.set during em.delete.

---

packages/tests/integration/migrations/1580658856631_author.ts

Should fix a test that recently became flakey.

chore: Make Author.favoriteBook deferred.

---

packages/orm/src/getProperties.ts

fix: Fix getters calling ReactiveField.get crashing.

---

packages/orm/src/Aliases.ts
packages/orm/src/EntityFilter.ts
packages/orm/src/QueryParser.ts
packages/orm/src/newTestInstance.ts
packages/tests/integration/src/EntityManager.queries.test.ts

feat: support `NULL` values on `IN` operator

---

packages/utils/src/connection.test.ts
packages/utils/src/connection.ts

Simple approach to resolve #1161

fix: simple pg connection string ssl handling

---

packages/orm/src/EntityFilter.ts
packages/orm/src/EntityGraphQLFilter.ts
packages/orm/src/QueryParser.ts
packages/orm/src/dataloaders/findDataLoader.ts
packages/orm/src/drivers/buildUtils.ts
packages/tests/integration/src/EntityManager.queries.test.ts

Direct support for [PSQL regular expression](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP) where clauses.

feat: Native support for regex operators on find

---

packages/orm/src/relations/RecursiveCollection.ts
packages/tests/integration/src/relations/RecursiveCollection.test.ts

When pointing to non-new grandparents.

fix: Fix parentsRecursive for new parents.

---

docs/docs/logging/_category_.json
docs/docs/logging/factory-logging.md
docs/docs/logging/field-logging.md
docs/docs/logging/reaction-logging.md
packages/orm/src/EntityManager.ts
packages/orm/src/FieldLogger.ts
packages/orm/src/ReactionsManager.ts
packages/orm/src/config.ts
packages/orm/src/createOrUpdatePartial.ts
packages/orm/src/fields.ts
packages/orm/src/index.ts
packages/orm/src/logging/FactoryLogger.ts
packages/orm/src/logging/FieldLogger.ts
packages/orm/src/logging/ReactionLogger.ts
packages/orm/src/newTestInstance.ts
packages/tests/integration/src/FieldLogging.test.ts
packages/tests/integration/src/relations/ReactiveReference.test.ts

To help debug "why did entity.firstName change from foo to bar".
Docs are wip...

feat: Add field logging

---

packages/codegen/src/codemods/index.ts
packages/orm/src/defaults.ts
packages/orm/src/drivers/PostgresDriver.ts
packages/orm/src/loadLens.ts
packages/orm/src/relations/hasManyThrough.ts
packages/orm/src/relations/hasOneThrough.ts
packages/tests/integration/src/EntityManager.lens.test.ts

fix: Fix lens traversal over undefined refs to collections.

---

.circleci/config.yml

This PR updates the versions of Node you're testing against. See inline comments for details.

chore: update node test versions

---

packages/orm/src/config.ts
packages/orm/src/configure.ts

Makes doing generic `add...Config` methods easier.

feat: Pass meta to the afterMetadata callback.

---

packages/orm/src/EntityManager.ts
packages/orm/src/defaults.ts

Turns out those todos were important.

fix: Fix defaults in subtypes.

---

packages/orm/src/newTestInstance.ts
packages/tests/integration/src/Entity.test.ts
packages/tests/integration/src/EntityManager.factories.test.ts
packages/tests/integration/src/EntityManager.test.ts
packages/tests/integration/src/entities/Author.test.ts

fix: Fail on invalid factory keys.

---

packages/graphql-resolver-utils/src/makeRunObjectField.ts

It can be useful for some scenarios.

fix: Pass root to the runField args lambda.

---

packages/orm/src/relations/CustomCollection.ts
packages/orm/src/relations/CustomReference.ts
packages/orm/src/relations/ManyToManyCollection.ts
packages/orm/src/relations/ManyToManyLargeCollection.ts
packages/orm/src/relations/ManyToOneReference.ts
packages/orm/src/relations/OneToManyCollection.ts
packages/orm/src/relations/OneToManyLargeCollection.ts
packages/orm/src/relations/OneToOneReference.ts
packages/orm/src/relations/PolymorphicReference.ts
packages/orm/src/relations/ReactiveReference.ts
packages/orm/src/relations/RecursiveCollection.ts
packages/orm/src/relations/Relation.ts

This is a baby-step towards `setDefault`s for o2m/m2m collections...

feat: Add Relation.hasBeenSet.

---

packages/orm/src/defaults.ts
packages/tests/integration/src/FieldLogging.test.ts

Just to make sure we don't hang.

fix: Resolve default deferreds in a promise.

---

packages/graphql-resolver-utils/src/saveEntity.ts
packages/orm/src/EntityManager.ts
packages/orm/src/defaults.ts
packages/orm/src/utils.ts
packages/tests/integration/src/FieldLogging.test.ts

Going to see if this fixes our flakey test.

fix: Use Promise.allSettled to avoid orphaned lambdas.

---

docs/docs/getting-started/installation.md

docs: fix link to sample app

---

packages/orm/src/utils.ts
packages/tests/integration/joist-config.json
packages/tests/integration/src/EntityManager.reactiveRules.test.tsx
packages/tests/integration/src/entities/codegen/PublisherCodegen.ts
packages/tests/integration/src/relations/OneToManyCollection.test.ts

feat: Allow ordering by ReactiveFields.

---

docs/docs/faq.md
docs/docs/getting-started/schema-assumptions.md

docs: Add surrogate keys requirement.

---

packages/orm/src/QueryParser.ts
packages/tests/temporal/src/entities/temporal.zonedDateTime.test.ts

When copying a user-provided `where` clause into a `ParsedFindQuery`, we create an AST of `{ kind: "between", value: ...user's array...} `.
This is fine, but mapToDb was directly mutating the array's values from domain types to db types, i.e. when doing Temporal ZonedDateTime conversion.
This fix just makes sure that we assign `filter.value` to a newly created array, which matches how the rest of the `mapDb` / `filter` rewriting works.

fix: Don't mutate between filters.

---

packages/orm/src/EntityManager.ts
packages/tests/integration/src/ClassTableInheritance.test.ts
packages/tests/integration/src/SingleTableInheritance.test.ts

fix: Check STI subtype in em.load/loadAll.

---

packages/codegen/src/assignTags.ts
packages/codegen/src/config.ts
packages/codegen/src/foreignKeyOrdering.ts
packages/codegen/src/index.ts
packages/orm/src/configure.ts

fix: Warn on duplicate tags in joist-config.

---

packages/test-utils/src/index.ts

chore: updating Matchers interface in test-utils to match expect package

---

packages/orm/src/changes.ts

This matches the fix for the m2m `hasChanged` / `hasUpdated`, that I forgot to apply to the o2m side.

fix: Add o2m.changes hasChanged.

---

packages/orm/src/changes.ts
packages/tests/integration/src/relations/ManyToManyCollection.test.ts
packages/tests/integration/src/relations/OneToManyCollection.test.ts

feat: Add o2m/m2m changes.originalEntities.

---

docs/src/docSorting.ts
docs/src/pages/llms-full.txt.ts
docs/src/pages/llms.txt.ts

Full credit to legend-state:
https://x.com/jmeistrich/status/1898575718310982101?t=XbxMK0ZdV8CSuncDjxKtKg&s=03

docs: Add llms.txt.

---

packages/orm/src/index.ts
packages/tests/integration/src/EntityManager.test.ts

This is not really a great idea, but should technically be allowed.

feat: Allow expliciting setting ids.

---

docs/src/content/docs/testing/test-factories.md

docs: Add docs for factories setting RFs.

---

packages/orm/src/configure.ts
packages/tests/integration/src/EntityManager.ctiQueries.test.ts
packages/tests/integration/src/entities/inserts.ts

Addresses https://github.com/joist-orm/joist-orm/issues/1432

fix: left outer join subtype restricted relations instead of inner join

---

docs/src/content/docs/faq.md
docs/src/content/docs/features/entity-manager.md
docs/src/content/docs/features/partial-update-apis.md
docs/src/content/docs/modeling/relations.md
packages/codegen/src/codemods/__testfixtures__/v1_245_0_upsert_rename.input.ts
packages/codegen/src/codemods/__testfixtures__/v1_245_0_upsert_rename.output.ts
packages/codegen/src/codemods/__tests__/v1_245_0_upsert_rename.test.ts
packages/codegen/src/codemods/v1_245_0_upsert_rename.ts
packages/graphql-resolver-utils/src/saveEntity.ts
packages/orm/src/EntityManager.ts
packages/orm/src/index.ts
packages/orm/src/upsert.ts
packages/tests/integration/src/EntityManager.upsert.test.ts
packages/tests/integration/src/entities/Author.ts
packages/tests/integration/src/relations/ManyToManyCollection.test.ts

feat: Rename createOrUpdatePartial to upsert

---

.gitignore
docs/src/tailwind.css
docs/tailwind.config.mjs

Inter Var for body/heading, and JetBrains Mono for code.
Ngl taking a cue from Atlassian Confluence.

docs: Use better fonts.

---

packages/orm/src/Aliases.ts
packages/orm/src/QueryParser.ts
packages/orm/src/drivers/buildUtils.ts
packages/tests/integration/src/EntityManager.queries.test.ts

feat: Add raw conditions to aliases.

---

packages/orm/src/EntityManager.ts
packages/orm/src/configure.ts
packages/tests/integration/src/EntityManager.test.ts

feat: add em.fork

---

packages/orm/src/configure.ts

tsx was suppressing the error the first time around, which then on the next configureMetadata invocation turned into a "tag is already configured" error.

fix: Fix tsx suppressing configure boot errors
