- packages/orm/src/EntityPersister.ts
When the column names are not all lowercase, bulk update fails due to the alias being quote-identified in the `from` clause but not in the assignments in the `update` clause.
In practice, using the migration helpers will prevent this scenario from occurring, as they do a good job of forcing everything into the snake_case paradigm. This would only affect users who are using Joist to maintain existing tables (who will probably run into issues with `created_at` and `updated_at` anyway) or people like me who naively create "raw" node-pg-migrate migrations and define their columns in the JS-conventional camelCase.
Similarly, I couldn't figure out how to get an integration test written to cover this scenario without creating a lot of code that would otherwise feel out of place in the …
> Quote-identify the column names in bulk update

- packages/integration-tests/src/collections/ManyToManyCollection.test.ts
- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Author.ts
- packages/integration-tests/src/utils.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/collections/ManyToManyCollection.ts
- packages/orm/src/collections/ManyToOneReference.ts
Just a first pass. Wondering if `ensureNotDeleted` should always allow pending-deletion entities/collections to be whitelisted.
> Run reactive validation rules on entity deletion.

- packages/integration-tests/src/collections/CustomReference.test.ts
- packages/integration-tests/src/entities/BookReview.ts
- packages/orm/src/collections/CustomReference.ts
- packages/orm/src/collections/ManyToManyCollection.ts
- packages/orm/src/collections/ManyToOneReference.ts
- packages/orm/src/index.ts
CustomReference encapsulates references that need some more complex logic than ManyToOneReference
> Added CustomReference

- packages/codegen/src/generateInitialEntityFile.ts
- packages/integration-tests/src/entities/Author.ts
- packages/integration-tests/src/entities/Book.ts
- packages/integration-tests/src/entities/BookReview.ts
- packages/integration-tests/src/entities/Publisher.ts
- packages/integration-tests/src/entities/Tag.ts
As we've discussed, having the constructor in the entity file is unnecessary and we don't intend for it to be modified anyways
> Removed the constructor from initial entity codegen file 

- README.markdown
- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/QueryBuilder.ts
This copies the joist-java value of 10,000 being "yeah something is probably wrong" but still allowing "large-ish" UoWs. It's not based on any actual performance/profiling/etc. numbers.
(Specifically we had a WIP query in dev OOM the graphql service by "load all the tasks in the db".)
We also add a `LIMIT 10,000` to all of our `find` queries, and then if a row set comes back with 10,000 rows, similarly throw of "sorry you made a `find` call that was too big, try something else". Doing this in theory protects the database from a "return 1 million rows by accident" query.
> Add a limit to the number of entities that can be loaded.

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/assignTags.ts
- packages/codegen/src/config.ts
- packages/codegen/src/generateMetadataFile.ts
- packages/codegen/src/index.ts
- packages/integration-tests/joist-codegen.json
- packages/integration-tests/src/EntityManager.lens.test.ts
- packages/integration-tests/src/EntityManager.populate.test.ts
- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/EntityManager.unsafe.test.ts
- packages/integration-tests/src/collections/CustomReference.test.ts
- packages/integration-tests/src/collections/ManyToManyCollection.test.ts
- packages/integration-tests/src/collections/OneToManyCollection.test.ts
- packages/integration-tests/src/collections/OneToOneReference.test.ts
- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Image.test.ts
- packages/integration-tests/src/entities/metadata.ts
- packages/orm/src/BaseEntity.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/EntityPersister.ts
- packages/orm/src/QueryBuilder.ts
- packages/orm/src/collections/CustomReference.ts
- packages/orm/src/collections/ManyToManyCollection.ts
- packages/orm/src/collections/ManyToOneReference.ts
- packages/orm/src/collections/OneToManyCollection.ts
- packages/orm/src/collections/OneToOneReference.ts
- packages/orm/src/index.ts
- packages/orm/src/keys.ts
- packages/orm/src/serde.ts
Somewhat proof-of-concept but it seems to be working pretty well/somewhat tempted to go ahead with it. At least don't see a reason to rule it out so far.
Basically our entity `.id`s already "look like strings" (still ints in the db), i.e. "1" / "2" / "3", and this changes the strings to be `"author:1"`, `"author:2"`, etc., so that as we pass around the id to the client / back to the server, we "really really really" know what entity it's for, and can verify that we didn't pass around the wrong id.
Historically when discussing tagged ids with other/pre-Homebound teams (i.e. at Remind, where a few of the "fancy tech shops" like FB/LinkedIn use tagged ids), the con of "well, that'd be a lot of boilerplate to go back/forth from tagged string / int-in-the-db" was one of the largest …
> Implement tagged ids

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/integration-tests/src/EntityManager.unsafe.test.ts
- packages/integration-tests/src/collections/ManyToManyCollection.test.ts
- packages/integration-tests/src/collections/OneToManyCollection.test.ts
- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/integration-tests/src/entities/BookAdvanceCodegen.ts
- packages/integration-tests/src/entities/BookCodegen.ts
- packages/integration-tests/src/entities/BookReviewCodegen.ts
- packages/integration-tests/src/entities/ImageCodegen.ts
- packages/integration-tests/src/entities/PublisherCodegen.ts
- packages/integration-tests/src/entities/TagCodegen.ts
- packages/integration-tests/src/entities/inserts.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/EntityPersister.ts
- packages/orm/src/collections/ManyToManyCollection.ts
- packages/orm/src/collections/OneToManyCollection.ts
- packages/orm/src/createOrUpdatePartial.ts
- packages/orm/src/index.ts
- packages/orm/src/utils.ts
We also look for 'delete' and 'remove' markers to either delete or
remove the method from the collection.
Right now 'delete' == `EntityManager.delete` i.e. not soft-deleting.
> Update partial methods to upsert collections.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/integration-tests/src/entities/BookAdvanceCodegen.ts
- packages/integration-tests/src/entities/BookCodegen.ts
- packages/integration-tests/src/entities/BookReviewCodegen.ts
- packages/integration-tests/src/entities/ImageCodegen.ts
- packages/integration-tests/src/entities/PublisherCodegen.ts
- packages/integration-tests/src/entities/TagCodegen.ts
- packages/orm/src/BaseEntity.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/collections/ManyToOneReference.ts
- packages/orm/src/collections/OneToManyCollection.ts
- packages/orm/src/getProperties.ts
- packages/orm/src/index.ts
Profiling a query that loaded ~2,000 entities showed large hot-spots
in `findExistingInstance` + `isEntity` + `getMetadata`. It was taking
~60 seconds and eventually timing out.
Adding an index for `findExistingInstance` dropped the time for the
same query to ~3 seconds and then it fails with a "too many entities"
error.
Kinda surprised at how much of a difference this makes, but when loading
~1000s of entities, findExistingInstance is called in a tight loop and
turns out O(N^2) is not a great idea.
> Optimize findExistingInstance and getMetadata.

- packages/integration-tests/package.json
- packages/orm/src/EntityManager.ts
`flush()` throws for validations, so in those cases it never actually gets to `this.contexty.cleanup()`, which leaves a whole bunch of empty maps here: https://github.com/stephenh/joist-ts/blob/master/packages/orm/src/contexty.ts#L3
> Fix leaking contexty resource

- packages/migration-utils/package.json
- yarn.lock
This will allow users to use utility functions with 5.x.
> Upgrade node-pg-migrate to 5.x

- README.markdown
This link was 404-ing because the file extension was not specified.
> Fix 'getting-started' documentation link in README

- packages/integration-tests/src/collections/OneToOneReference.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/collections/AbstractRelationImpl.ts
- packages/orm/src/collections/CustomCollection.ts
- packages/orm/src/collections/CustomReference.ts
- packages/orm/src/collections/ManyToManyCollection.ts
- packages/orm/src/collections/ManyToOneReference.ts
- packages/orm/src/collections/OneToManyCollection.ts
- packages/orm/src/collections/OneToOneReference.ts
- packages/orm/src/index.ts
Makes their use more explicit.  Also added a `getRelations` helper method to replace a commonly repeated pattern.
> renamed relation onDelete callbacks

- packages/integration-tests/jest.config.js
- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/setupTestEnv.ts
- packages/orm/src/index.ts
This relates to #65. It's the same issue, just another place we need to use the new `equal` method vs. `===`.
> Ignore date sets of same value

- packages/codegen/package.json
- packages/graphql-codegen/package.json
- packages/integration-tests/package.json
- packages/migration-utils/package.json
- packages/orm/package.json
This allows users to easily jump into the proper place in the monorepo via `npm repo` from the CLI, e.g.
```
npm repo joist-orm
```
> Add `repository` to package.json files

- packages/integration-tests/Makefile
The `db-wait` task was actually already defined and used for CircleCI, just not in the `Makefile`, which is used for running locally.
Closes #69
> Wait for DB when running locally

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
This PR adds a new method, `loadAllIfExists`, which works just like `loadAll`, but it does not throw an `Error` if a given id cannot be found in the database.
> Add loadAllIfExists

- README.markdown
- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/generateEnumFile.ts
- packages/codegen/src/index.ts
- packages/codegen/src/utils.ts
- packages/graphql-codegen/src/generateEnumDetailResolvers.ts
- packages/graphql-codegen/src/generateEnumsGraphql.ts
- packages/graphql-codegen/src/generateGraphqlCodegen.test.ts
- packages/graphql-codegen/src/generateGraphqlCodegen.ts
- packages/graphql-codegen/src/generateGraphqlSchemaFiles.ts
- packages/graphql-codegen/src/generateObjectResolvers.ts
- packages/graphql-codegen/src/generateSaveResolvers.ts
- packages/graphql-codegen/src/graphqlUtils.ts
- packages/graphql-codegen/src/index.ts
- packages/graphql-codegen/tsconfig.json
- packages/integration-tests/schema/enums.graphql
- packages/integration-tests/src/generated/graphql-types.ts
- packages/integration-tests/src/resolvers/enumResolvers.ts
This takes support for extra columns in enum tables all of the way through the generated graphql code as well as the resolvers.
`enums.graphql`
`enumResolvers.ts`
> Include extraPrimitives from enum tables in graphql and resolvers

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/codegen/src/utils.ts
- packages/graphql-codegen/src/generateEnumsGraphql.ts
- packages/graphql-codegen/src/generateGraphqlSchemaFiles.test.ts
- packages/graphql-codegen/src/graphqlUtils.ts
Added explicit types for PrimitiveFIeld's columnType / fieldType so they aren't just string and fixed a circular dependency issue in graphql-codegen
> Circular Dependency Fix

- packages/integration-tests/src/EntityManager.populate.test.ts
- packages/orm/src/EntityManager.ts
From the linked TS issue. The approach is similar to before (...with the caveat that I am still just cargo culting it), but with a new `Const` type that cleans up the `N extends Narrowable` extra/throw-away generic from all of the declaration sites.
> Use cleaner Narrowable/Const implementation.

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
This change makes `em.flush()` return changed entities so that clients can know what specifically changed as a result of their queries
> [Ranch-1048] Return Changed Entities from `em.flush()`

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
Clearing out the original data for deleted objects such that we don't re-run them in follow-on flushes within a transaction.
> allow for deleting an object in a transaction

- packages/orm/src/EntityManager.ts
- packages/orm/src/index.ts
- Make `ValidationError.entity` optional so that we don't need to specify it when making potential operations
- Export `ValidationRuleResult` type to avoid need to make a similar one in graphql-service
- Stamp in the `ValidationError.entity` field as part of `coerceError`
> Enhance ValidationError to make it work better with potential operations

- .circleci/config.yml
- packages/integration-tests/docker-compose.yml
- packages/integration-tests/local.docker.env
- packages/integration-tests/package.json
- packages/integration-tests/tests.dockerfile
- tests.sh
- yarn.lock
This PR reworks the CircleCI Build process to test Joist against multiple versions of Node. It also enables the JUnit test reporter so we get pretty CircleCI test reports.
> chore(build): rework circleci config (matrix build, test summarization)

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/config.test.ts
- packages/codegen/src/config.ts
- packages/integration-tests/joist-codegen.json
- packages/integration-tests/migrations/1580658856631_author.ts
Laide ran into an issue where she could not ignore a required column, even though it had a default value.
This PR adds support for that capability.
> feat: Ability to ignore notNull columns with default values

- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Author.ts
- packages/orm/src/BaseEntity.ts
- packages/orm/src/EntityManager.ts
`isNewEntity` should now return true during an `afterCommit` if the entity was inserted as part of that flush
> refactored isNewEntity behavior in afterCommit hooks

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/integration-tests/src/entities/BookAdvanceCodegen.ts
- packages/integration-tests/src/entities/ImageCodegen.ts
- packages/integration-tests/src/entities/PublisherCodegen.ts
I wrote:
```
name() {
const detail = ProcurementRequestTypes.getByCode(this.type);
return `${detail.name} Request ${this.idUntagged}`;
}
```
And wanted it to be `this.typeDetails.name` instead
> Add getters for enum details.

- packages/orm/src/EntityManager.ts
- packages/orm/src/collections/ManyToManyCollection.ts
- packages/orm/src/collections/ManyToOneReference.ts
- packages/orm/src/collections/OneToManyCollection.ts
- packages/orm/src/collections/OneToOneReference.ts
- packages/orm/src/index.ts
- packages/orm/src/utils.ts
also refactored `isReference` / `isCollection` to actually check against the concrete implementation classes instead of just seeing if the object looked like a relation
> added explicit isLoaded to all relation types

- .circleci/config.yml
- packages/orm/package.json
This fix in Node 16.3.0 should fix compatibility with Joist / jest: https://github.com/nodejs/node/pull/38821
> chore: re-enable node 16 testing

- packages/integration-tests/src/EntityManager.createOrUpdatePartial.test.ts
- packages/orm/src/createOrUpdatePartial.ts
- packages/orm/src/index.ts
This addresses @haislip 's use case where the client might send in `children: [{ delete: true, ... }, { delete: false }, ...]` but they might also send in `children: []` but that doesn't mean "clear the collection" it just means "there are no incremental operations to perform".
Now the resolver (or even the client) can include a throw-away `{ op: "incremental" }` that won't do anything other than turn on the incremental/non-exhaustive behavior.
> Add 'incremental' operation to handle when sets might be empty.

- packages/graphql-codegen/src/generateEnumsGraphql.ts
- packages/graphql-codegen/src/generateGraphqlSchemaFiles.test.ts
- packages/graphql-codegen/src/generateGraphqlSchemaFiles.ts
- packages/graphql-codegen/src/graphqlUtils.ts
To fix all of our `createdAt`s being `Date`s and so not sorting correctly if they happen to be on the same day.
> Scaffold DateTimes for ...At fields.

- docs/misc-features.markdown
- packages/integration-tests/src/entities/Author.test.ts
- packages/orm/src/EntityManager.ts
This PR adds a new `skipValidation` option to the `flush` method. This allows for certain cases where you want to forcibly override validations.
> feat: add skipValidation option to flush method

- packages/integration-tests/src/EntityManager.queries.memory.test.ts
- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/orm/src/QueryBuilder.ts
- packages/orm/src/drivers/InMemoryDriver.ts
The types supported `{ gte: 1, lte: 5 }` but the parsing did not.
> Fix: Support multiple primitive filters as ANDs.

- packages/integration-tests/src/entities/Book.factories.ts
- packages/integration-tests/src/entities/Book.test.ts
- packages/orm/src/newTestInstance.ts
I.e. if a parent factory has:
```
export function newParent(...) {
return newTestInstance(em, {
// Always have one child
children: [{}],
...opts
});
}
```
But a test is creating the child "bottom up", i.e. doing:
```
newChild(em, { parent: ... });
```
Then we know the parent is going to get a list of children already (from
the one that is currently being created), so we don't need its `children:
[{}]` default to apply.
So we send in `opts.children: null`, as if the programmer had written
that by hand, such that the `...opts` convention of the factories will
write over the `children: [{}]` default.
> Better handle children creating parents via factories.

- packages/integration-tests/src/EntityManager.factories.test.ts
- packages/orm/src/newTestInstance.ts
Previously we looked them up after a factory has called newTestInstance,
which worked but meant that the factory's internal default behavior
logic might kick in, instead of using the entity passed in `use`.
> Pass use entities directly to factories.

- packages/integration-tests/src/EntityManager.factories.test.ts
- packages/orm/src/index.ts
- packages/orm/src/newTestInstance.ts
Also converts `use` internally over to a map to avoid less sequential
scanning of things.
> Fix calling new with both use & a required field set as undefined.

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/drivers/PostgresDriver.ts
Turns out array columns where just horribly broken because of how
our UPDATE statements work.
We had used a trick where, to update 10 authors in 1 SQL statement,
we send 1 SQL UPDATE and then make a mini-temp-table by sending
in 10 first names, 10 last names, etc., each as an array, and then
`unnest`-ing each array into a given column, i.e. we'd get a temp
table with 10 rows, with each row's first name/last name/etc.
When I added array support, I tried to treat the array column in
this scenario as a "list of lists", i.e. something like 1st entity's
colors is [1], 2nd entity's colors is [2, 3], so send over [[1], [2,3]]
as a 2-dimensional array.
However, 2-dimensional arrays are not sparse, i.e. they have to be
[[1, 4], [2, 3]], which of course just doesn't make sense/can't work
for what I …
> Fix array columns.

- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Author.ts
- packages/orm/src/changes.ts
It seems like we almost always do `foo.hasChanged || isNewEntity`, i.e. `hasChanged` should just be true for set fields on new entities.
> Change hasChanged to be true on create.

- packages/integration-tests/src/entities/Author.test.ts
- packages/orm/src/changes.ts
So that call sites can pick whether they want "changed at all" or "updated but not the initial create".
> Add hasUpdated as prior hasChanges behavior.

- packages/integration-tests/src/relations/ManyToManyCollection.test.ts
- packages/orm/src/drivers/PostgresDriver.ts
If a user adds an entity to an unloaded m2m, and that entity happened to
already be in the m2m table, we will avoid the unique constraint
conflict and just ues the existing row.
Fixes #179
> feat: Automatically dedup adds to m2ms.

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/drivers/PostgresDriver.ts
- packages/orm/src/keys.ts
Per discussions, this is pretty easy for the ORM to keep track of and
just handle for us, and we can't really be sure how often it's happening
today because we can't detect it (although it is almost certainly
basically never).
> Implement optimistic locking.

- packages/orm/src/EntityManager.ts
Little bit of cargo-culting, but avoiding `async` functions where we don't need them.
> chore: Remove some awaits.

- packages/codegen/tsconfig.json
- packages/graphql-codegen/tsconfig.json
- packages/integration-tests/tsconfig.json
- packages/migration-utils/tsconfig.json
- packages/orm/src/EntityManager.ts
- packages/orm/src/dataloaders/oneToOneDataLoader.ts
- packages/orm/tsconfig.json
- packages/test-utils/tsconfig.json
- packages/utils/tsconfig.json
With `Promise.all([...hooks...])` if one hook failed (_cough_ `Bill.beforeDelete`-cannot-delete-a-paid-bill _cough_), then `Promise.all` would immediately return.
However, the remaining hooks are not proactively aborted, and continue on their merry way.
This can lead to confusing things like:
- the failed hook makes `em.flush` early return
- the test stops and the pool shuts down
- one of the remaining hooks, still navigating through its populate hint, tries to load an entity/collection
- the connection pool throws a `TimeoutError` (??)
- in general various lingering lambdas confuse jest and subsequent tests
> fix: Fix faulty hooks orphaning the remaining hooks.

- docs/docs/getting-started/adding-to-your-project.md
- packages/integration-tests/local.env
- packages/integration-tests/src/setupDbTests.ts
- packages/integration-tests/src/setupMemoryTests.ts
- packages/tests/uuid-ids/local.env
- packages/tests/uuid-ids/src/setupDbTests.ts
- packages/utils/src/connection.test.ts
- packages/utils/src/connection.ts
It was a legacy RDS cruft-ism that we don't need anymore.
Replaced with DATABASE_URL (a connection string) or DB_USER/PASSWORD/HOST/PORT/DATABASE.
> Remove DATABASE_CONNECTION_INFO.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/integration-tests/src/entities/BookAdvanceCodegen.ts
- packages/integration-tests/src/entities/BookCodegen.ts
- packages/integration-tests/src/entities/BookReviewCodegen.ts
- packages/integration-tests/src/entities/CommentCodegen.ts
- packages/integration-tests/src/entities/CriticCodegen.ts
- packages/integration-tests/src/entities/ImageCodegen.ts
- packages/integration-tests/src/entities/PublisherCodegen.ts
- packages/integration-tests/src/entities/TagCodegen.ts
- packages/orm/src/EntityManager.ts
- packages/tests/uuid-ids/src/entities/AuthorCodegen.ts
- packages/tests/uuid-ids/src/entities/BookCodegen.ts
Pretty minor, but it avoids a throw-away `__types` field on each entity instance, which only existed for the type system to do inferred / type lookups.
> Borrow the __orm field for the __types hints.

- packages/integration-tests/src/relations/ManyToManyCollection.test.ts
- packages/integration-tests/src/relations/OneToManyCollection.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/dataloaders/manyToManyDataLoader.ts
- packages/orm/src/dataloaders/manyToManyFindDataLoader.ts
- packages/orm/src/dataloaders/oneToManyDataLoader.ts
- packages/orm/src/dataloaders/oneToManyFindDataLoader.ts
- packages/orm/src/drivers/InMemoryDriver.ts
- packages/orm/src/drivers/PostgresDriver.ts
- packages/orm/src/drivers/driver.ts
- packages/orm/src/relations/Collection.ts
- packages/orm/src/relations/CustomCollection.ts
- packages/orm/src/relations/ManyToManyCollection.ts
- packages/orm/src/relations/OneToManyCollection.ts
Fixes #244
This also re-implements this existing `Collection.find` to not trigger a full load of the collection.
My assumption is that we implemented that as a "most pragmatic / easiest impl", but I believe as we have more and more large collections, being strict / more precise about what `.find` does is better.
> feat: Add ManyToMany.includes.

- packages/integration-tests/src/EntityManager.factories.test.ts
- packages/integration-tests/src/entities/Publisher.factories.ts
- packages/orm/src/newTestInstance.ts
If the child factory is the one invoking the parent anyway.
I.e. `newBook` -> creates an author, if the `newAuthor` happened to
have `books: [{}]` in it, we should not create yet-another-book.
> fix: Fix parent factories should skip default children

- packages/integration-tests/src/EntityManager.factories.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/newTestInstance.ts
Meant to both de-dup a bunch of code within `newTestInstance` as well be a public API for application factories to provide their own default behavior.
> feat: Add maybeNew for factories

- packages/integration-tests/src/alignedAnsiStyleSerializer.ts
- packages/integration-tests/src/toMatchEntity.test.ts
- packages/test-utils/jest.config.js
- packages/test-utils/src/toMatchEntity.ts
Fixes #256 . We already had `toMatchEntity` upstreamed, but this adds some tests/polish, and then will follow up with removing the internal copy.
> fix: Polish toMatchEntity.

- packages/orm/src/newTestInstance.ts
So that things like `andSigned: true` args are supported.
> fix: Update maybeNew to use ActualFactoryOpts.

- package.json
Root package.json was missing `private: true`
> fix: Make the root workspace private

- packages/orm/src/index.ts
- packages/orm/src/utils.ts
Just as a shorter way of doing `foo as New<SomeLongEntityName>` --> `asNew(foo)`.
Currently just a cast.
> fix: Add asNew helper method.

- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/relations/PolymorphicReference.test.ts
- packages/orm/src/BaseEntity.ts
So that `console.log(anEntity)` doesn't output a ton of noise about the entity's internal state.
We could eventually have it return the internal state, like if depth is zero...but this is simplest for now.
> feat: Implement custom inspect method.

- packages/orm/src/keys.ts
This PR brings the `fail` utils function in to `keys.ts` to prevent a naming conflict with `jest`'s `fail()` function.
> fix: Use joist util fail

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
Previously clone would both find + fixup entities in a single pass.
This made it hard/impossible for clone to go back and update
already-cloned entities to point to new downstream clones.
I.e. when cloning author -> book, author has a currentDraftBook field,
but we've not even cloned it's books yet, so would not fix up the
relation, and leave a newly cloned author pointing to the original
author's book.
This PR breaks up clone into three distinct phases of 1) find, 2)
clone, and 3) fixup.
The upshot is that the fixup phase now knows about all clones, i.e.
we can point `author.currentDraftBook` to the new book.
> feat: Make clone smarter.

- packages/integration-tests/src/alignedAnsiStyleSerializer.ts
- packages/integration-tests/src/toMatchEntity.test.ts
Remove all ANSI chars b/c we don't really need to assert against them,
and also when running `yarn test` as a top-level command, the ANSI
chars are not output for some reason, so the snapshots would fail.
> chore: Simplify toMatchEntity test's ANSI output.

- packages/integration-tests/src/entities/Author.test.ts
- packages/orm/src/rules.ts
This is admittedly solely for backwards compatibility for now; maybe
we'll do something fancier later.
> fix: Don't capital case field name.

- packages/integration-tests/src/EntityManager.clone.test.ts
- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
Enhancements to `em.clone` to allow for:
1) Optional `skipIf` function to avoid cloning an entity deep in the object graph if desired (ex: don't clone soft-deleted entities)
2) Optional `postClone` function to be called for each `original/clone` pair
3) Optional ability to pass an array of objects to be clones, instead of just 1
> feat: [SC-15953] em.clone enhancements

- packages/integration-tests/src/entities/Author.test.ts
- packages/orm/src/Todo.ts
I.e. if you need to fix bugs in the derived logic.
> feat: Recalc all async derived fields on touch.

- packages/integration-tests/src/EntityManager.reactiveRules.test.tsx
- packages/integration-tests/src/entities/Author.ts
- packages/orm/src/EntityManager.ts
We need to run the hooks first, to see if they have any side effects,
and then detect which rules & async derived fields we need re-calc.
...granted, this begs the question of what about hooks that want to
observe the latest derived value? This is probably where we need a
DAG of hook/value dependencies and invoke them in topo order instead
of fixed.
> fix: Fix async derived fields not triggering from hook changes.

- packages/integration-tests/src/EntityManager.reactiveRules.test.tsx
- packages/integration-tests/src/entities/Book.ts
- packages/integration-tests/src/entities/BookReview.ts
- packages/integration-tests/src/getProperties.test.ts
- packages/integration-tests/src/reactiveHints.test.ts
- packages/orm/src/reactiveHints.ts
The existing code was basically checking "is `Book.reviews` read only?" instead of checking "is `BookReviews.book` read only?"
This fixes that.
That said, we don't want these reactive hints for immutable fields to go _completely_ away, b/c they still need to fire on create & delete.
So really this PR is no change in semantics; b/c of the bug of checking the wrong read only, o2m/o2o reactive hints never took advantage of the immutable field optimization, but again we couldn't do that anyway b/c we need them for creates & deletes.
But, it's still nice to explicitly cover it, and drop the `book` field from the reactions file, just b/c it does stand out of "hey this field is immutable, so why am I reacting to it?".
> fix: Check the other side's readonly for o2m/o2o reactive hints.

- docs/docs/getting-started/configuration.md
- docs/docs/getting-started/schema-assumptions.md
- packages/codegen/src/config.ts
- packages/codegen/src/utils.ts
- packages/tests/schema-misc/joist-codegen.json
It's more intuitive to read "required: true" than flip the double
native of "optional: false".
> feat: Rename TimestampConfig.optional to required.

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/orm/src/QueryBuilder.ts
The code already worked b/c of how `QueryBuilder` was calling `column.mapToDb(entity)`.
> fix: Fix filtering on an entity list for IN.

- packages/integration-tests/src/reactiveHints.test.ts
- packages/orm/src/BaseEntity.ts
The Reacted type is stricter than Loaded, b/c it is a field-level
subview of the entity, but that means since Loaded is a superset
of Reacted, we should be able to pass a Loaded entity to a function
that accepts Reacted.
> feat: Allow passing Loaded to functions that accept Reacted.

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/loadLens.ts
This allows applying a lens-based navigation to multiple starting
entities, instead of a single entity via `Entity.load`, i.e.:
```
const publishers = await em.loadLens(books, b => b.author.publisher);
```
Vs. today you can only use the `b => b.author.publisher` syntax if you're
starting at a single book and do `await book.load(b => ...)`.
> feat: Add EntityManager.loadLens.

- docs/docs/modeling/derived-fields.md
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/codegen/src/symbols.ts
- packages/integration-tests/src/EntityManager.reactiveRules.test.tsx
- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Author.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/integration-tests/src/entities/BookReview.ts
- packages/integration-tests/src/entities/BookReviewCodegen.ts
- packages/orm/src/BaseEntity.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/Todo.ts
- packages/orm/src/config.ts
- packages/orm/src/getProperties.ts
- packages/orm/src/index.ts
- packages/orm/src/relations/ManyToManyCollection.ts
- packages/orm/src/relations/ManyToOneReference.ts
- packages/orm/src/relations/hasDerivedAsyncProperty.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
- packages/orm/src/relations/index.ts
This replaces the previous config based API, with the benefits that:
* Users can explicitly call the properties to get the latest value,
i.e. from other derived properties.
* If the load hint is satisified, users can call the property
immediately after creating the entity, w/o waiting for em.flush to
calc the value.
* If the property is loaded, it will always calc the latest value
instead of potentially using an outdated value from the last
em.flush.
> feat: Add PersistedAsyncProperty for derived async fields.

- packages/orm/src/drivers/PostgresDriver.ts
The theory is that the transaction conflict analyzer cannot see into
the unnest clauses to tell that multiple updates don't conflict on
each other.
> fix: Remove unnest approach to avoid txn conflicts.

- packages/codegen/package.json
- packages/codegen/src/config.ts
- packages/codegen/src/index.ts
- packages/codegen/src/utils.ts
- packages/graphql-codegen/package.json
- packages/graphql-codegen/src/graphqlUtils.ts
- packages/graphql-codegen/src/history.ts
- packages/integration-tests/package.json
- yarn.lock
Still using prettier for graphql formatting, but we can at least prevent loading prettier-plugin-organize-imports, which is expensive b/c it does a `require("typescript")`.
> feat: Use @dprint/json for config and history files.

- packages/codegen/src/EntityDbMetadata.ts
- packages/integration-tests/src/EntityManager.populate.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/config.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/index.ts
This fixes `em.populate` doing too much fan-out, i.e. if we do something like:
```
em.populate([publishers], { authors: { books: { author: "publisher" } })
```
Or other sufficiently-deep load hint, because of the flexibility+opaqueness of load hints (where the contract is basically "just call `.load` and see what happens"--which is great b/c it allows a very flexible contract w/o needing to like pre-plan out an entire N layer 'query plan'), it meant that if we had 10,000 books all with the same author, we'd call:
* book1.author.load --> new promise for a:1
* book2.author.load --> new promise for a:2
* book3.author.load --> new promise for a:3
* ...repeat for 10k promises...
And then if we wanted to load `author.publisher`, all of those 10k promises would do their _own_:
* Load …
> fix: Fix populate performance

- packages/integration-tests/src/EntityManager.reactiveRules.test.tsx
- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Book.ts
- packages/integration-tests/src/entities/Publisher.ts
- packages/integration-tests/src/getProperties.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/reactiveHints.ts
- packages/orm/src/relations/hasAsyncProperty.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
This includes both non-persisted `AsyncProperty` and `PersistedAsyncProperty`s.
`PersistedAsyncProperty` basically worked for free, b/c a rule depending on persisted field would already get the transitiveness basically for free:
1) new `Book` recalcs the `Author.numberOfBooks` persisted property,
2) `Author`'s reactive validations see `numberOfBooks` changing and queue the `Publisher` rule to rerun.
(Note that `em.flush`s design of "loop over all pending entities first, then do a single validate pass" worked out really well to avoid ordering issues, i.e. we don't have to worry about the Author's reactive validations (step 2) having already been evaluated before the step 1 recalc ran, which if it did happen would mean missing that `numberOfBook`s _will_ change but just hasn't yet.)
For …
> feat: Support async properties in reactive hints.

- packages/codegen/src/EntityDbMetadata.test.ts
- packages/codegen/src/EntityDbMetadata.ts
The code should have been doing a `replaceStart`, i.e. to make `Book.bookReviews` more succinct as `Book.reviews`, but not `Variable.projectVariables` into `Variable.projects` (where the `Variable` is a _suffix_ of some other entity, and dropping suffixes more dramatically changes meanings).
> fix: Don't drop mid-string entity names.

- packages/integration-tests/src/EntityManager.createOrUpdatePartial.test.ts
- packages/integration-tests/src/relations/OneToManyCollection.test.ts
- packages/orm/src/index.ts
- packages/orm/src/relations/ManyToOneReference.ts
- packages/orm/src/relations/OneToManyCollection.ts
Where ownership is determined by cascade deletion from the parent to the child.
> feat: Calling o2m.set(values) deletes owned children

- packages/integration-tests/src/toMatchEntity.test.ts
- packages/test-utils/src/toMatchEntity.ts
I.e. results of GraphQL resolvers.
> fix: Allow toMatchEntity to work on object literals.

- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Author.ts
- packages/orm/src/index.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
We were using the reactiveHint which has primitives in it like `firstName` that will never be loaded / pass isLoaded check.
If we use the load hint, then we'll only have relations, which is what `isLoaded` expects to see.
> fix: Fix calling isLoaded with the wrong hint.

- packages/orm/src/config.ts
For some reason using tsx means `error.stack` is more verbose and has a few lines at the beginning that we did not have before...maybe b/c of going through the loader API?
Not entirely sure, but this fixes it by ignoring any lines in the stack that are not `at` lines in the souce.
> fix: Fix getCallerName when running via tsx.

- packages/integration-tests/src/EntityManager.assignNewIds.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/drivers/IdAssigner.ts
- packages/orm/src/drivers/InMemoryDriver.ts
- packages/orm/src/drivers/PostgresDriver.ts
- packages/orm/src/drivers/driver.ts
For cases where you need to know the ID of an entity prior to it being flushed, you can now call `EntityManager.assignNewIds`.
> feat: Add EntityManager.assignNewIds capability

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
This fixes a max stack trace exceeded observed when using the original commit in graphql-service
> fix: Ensure sameEntity works even if an ID has been assigned to a new entity

- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Author.ts
- packages/orm/src/loadHints.ts
Discovered due to this failing test in GQL service
When the `changeOrder` was loaded but null, we would still attempt to recurse into `isLoaded` again giving the message above.
> fix: Issue where isLoaded does not correctly handle nullable loaded references

- packages/integration-tests/src/Entity.test.ts
- packages/orm/src/BaseEntity.ts
- packages/orm/src/Entity.ts
- packages/orm/src/dataloaders/oneToManyDataLoader.ts
- packages/orm/src/getProperties.ts
- packages/orm/src/relations/CustomCollection.ts
- packages/orm/src/relations/CustomReference.ts
- packages/orm/src/relations/ManyToManyCollection.ts
- packages/orm/src/relations/ManyToOneReference.ts
- packages/orm/src/relations/OneToManyCollection.ts
- packages/orm/src/relations/OneToOneReference.ts
- packages/orm/src/relations/hasAsyncProperty.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
This keeps code that wants to recursively compare/diff entities (via `Object.keys`, e.g. Jest's `toMatchObject` and IntelliJ's Jest integration) from getting bogged down in the extremely large `metadata` data.
> fix: Make metadata inaccessible via Object.keys enumeration.

- README.markdown
- packages/codegen/src/EntityDbMetadata.ts
- packages/integration-tests/migrations/1580658856631_author.ts
Here is the fix discussed for partial unique indexes resulting in o2o collection instead of o2m.
The key point to observe in the diffs is that now there are no changes to the metadata. Publisher still has an `authors: Author[]` collection.
> fix: Correctly handle partial unique indexes

- docs/docs/features/soft-deletes.md
- packages/integration-tests/src/EntityManager.softDeletes.test.ts
- packages/orm/src/loadLens.ts
- packages/orm/src/relations/ManyToOneReference.ts
In retrospect, it changes the return type too much (from Entity to undefined) for what can be a pretty common case.
(Vs. the "skip hard-deleted entities" logic that we have now, which is rare enough that it's worth the return type disruption.)
> fix: Don't skip soft-deleted entity in m2o.get.

- packages/integration-tests/src/toMatchEntity.test.ts
- packages/test-utils/src/toMatchEntity.ts
Otherwise the test assertion is unclear if soft-deleted entities are soft-deleted-and-being-suppressed or actually hard-deleted and literally not there anymore.
> fix: Update toMatchEntity to include soft-deleted entities.

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/integration-tests/src/Inheritance.test.ts
- packages/orm/src/QueryBuilder.ts
Included a regression test that failed before the revert.
> fix: Revert q&d attempt at cross-table em.find support.

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/QueryBuilder.ts
> fix: Skip the suffix for the first abbreviation.

- packages/integration-tests/benchmark.ts
- packages/integration-tests/package.json
- packages/integration-tests/run.sh
- yarn.lock
* Clone `joist-ts`
* `yarn`
* `make db`
* `yarn codegen` to create `flush_database` function
* `cd packages/integration-tests`
* `./run.sh benchmark.ts`
```
$ ./run.sh benchmark.ts
{ numberOfEntities: 20, iterations: 100, serial: false }
- - - - - - - - - - - - - - - - - Performance - - - - - - - - - - - - - - - - -
Knex 20 Authors individually:
238.35666 ms (+/- 14.21493 ms) from 100 iterations
Knex 20 Authors with VALUES:
21.89214 ms (+/- 2.2392 ms) from 100 iterations
Postgres.js 20 Authors individually:
92.01067 ms (+/- 6.92755 ms) from 100 iterations
Postgres.js 20 Authors individual but pipelined:
26.8869 ms (+/- 2.63665 ms) from 100 iterations
Postgres.js 20 Authors with VALUES:
19.96301 ms (+/- 1.41438 ms) from 100 iterations
Knex 20 Authors & 20 Books with VALUES in txn:
28.94912 …
```
> chore: Add benchmarks with postgres.js.

- packages/codegen/src/generateFactoriesFiles.ts
- packages/integration-tests/src/EntityManager.factories.test.ts
- packages/integration-tests/src/entities/Book.factories.ts
- packages/orm/src/newTestInstance.ts
It's ~somewhat common for a factory to have a default it wants to apply, like:
```ts
export function newBook(em: EntityManager, opts: FactoryOpts<Book> = {}): DeepNew<Book> {
return newTestInstance(em, Book, {
author: { age: 40 },
...opts,
});
}
```
And then a test want to customize some _other_ author field, like `firstName`:
```ts
const b1 = newBook(em, {
author: { firstName: "long name" }
});
```
Which, as written so far, will drop the `{ age: 40 }` default from the `newBook` factory.
To prevent this, historically factories had to manually merge their `{ age: 40 }` defaults with the test's `{ firstName: "long name" }` overrides, which initially seems trivial:
```ts
export function newBook(em: EntityManager, opts: FactoryOpts<Book> = {}): DeepNew<Book> {
const { author, ...rest } = …
```
> feat: Let newTestInstance deep merge opts.

- packages/integration-tests/joist-config.json
- packages/integration-tests/migrations/1580658856631_author.ts
- packages/integration-tests/schema/.history.json
- packages/integration-tests/schema/smallPublisher.graphql
- packages/integration-tests/src/Inheritance.test.ts
- packages/integration-tests/src/entities/SmallPublisher.ts
- packages/integration-tests/src/entities/SmallPublisherCodegen.ts
- packages/integration-tests/src/entities/metadata.ts
- packages/integration-tests/src/relations/OneToManyCollection.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/index.ts
- packages/orm/src/relations/OneToManyCollection.ts
The derived field on the subtype itself worked, but entities of the _other_ subtype would blow up.
For example, `SmallPublisher.allAuthorNames` is a derived field.
If an Author points to a SmallPublisher, we can follow a1 -> publishers -> recalc sp1[allAuthorNames].
But if an Author points to a LargePublisher, if we try to follow a1 -> publishers -> recalc lp1[allAuthorNames], it will NPE because the LargePublisher doesn't have an `allAuthorNames` field.
Which is fine, the Author, when it said "hey tell my publisher to recalc things" can't know "is this publisher large or small?", so we just have to detect/infer that at runtime, by handling the "field does not exist" as a heuristic for "ah, because its not on this subtype".
---
This PR also happens to fix an unrelated bug with o2m …
> fix: Fix derived fields on subtypes.

- packages/integration-tests/src/EntityManager.reactiveRules.test.tsx
- packages/integration-tests/src/Inheritance.test.ts
- packages/integration-tests/src/entities/SmallPublisher.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/config.ts
- packages/orm/src/index.ts
Reactive rules correctly worked on the subtype itself, but also would incorrectly fire on all types and not just the subtype they were added to.
> fix: Fix reactive rules on subtypes.

- docs/docs/testing/test-factories.md
- packages/integration-tests/src/EntityManager.factories.test.ts
- packages/integration-tests/src/entities/Author.factories.ts
- packages/integration-tests/src/entities/BookReview.factories.ts
- packages/orm/src/newTestInstance.ts
I've seen a few hand-written ways of "oh wait, ignore those factory defaults that _usually_ we want", so this provides a pattern to opt-out of defaults:
```ts
newBook(em, { useFactoryDefaults: false });
```
This will ignore any `Book.factories.ts` defaults but will still use the "title is a required field" defaults.
To ignore literally all defaults, you can use "none":
```ts
newBook(em, { useFactoryDefaults: "none" });
```
---
...currently in this PR, you get "all or none" of the factory defaults, maybe it would be cute to support only ignoring specific fields? Like:
```ts
newBook(em, { ignoreDefaults: "title" });
```
Although at that point, shouldn't the test just pass their own title:
```ts
newBook(em, { title: undefined });
```
Probably. Sticking with the "all or nothing" seems better; …
> feat: Add useFactoryDefaults escape hatch.

- packages/integration-tests/src/EntityManager.reactiveRules.test.tsx
- packages/integration-tests/src/Inheritance.test.ts
- packages/orm/src/EntityManager.ts
Reactively calculating subtype-only derived values was working correctly, but the initial "calc (non-reactively) on new entity" was only running for base type derived values, and not subtype-only derived values.
> fix: Fix initial calc of subtype-only derived values.

- packages/integration-tests/src/Inheritance.test.ts
- packages/integration-tests/src/relations/OneToManyCollection.test.ts
- packages/orm/src/relations/OneToManyCollection.ts
We recently fixed an issue with `author.books.get` missing books that had been set to the author, before the author itself was loaded from the db.
The fix was correct, but used a naive "scan all the things" implementation which really does not perform well in large UoWs, like over 10k entities.
Note that merely "scanning all loaded entities" (and commenting out the `.includes` n^2 issue) still results in too much of a performance regression, so we'll have to find a non-scanning way of fixing this bug.
The original "author missing a book" bug has existed for a long time and doesn't seem to have caused us any issues, so shouldn't be a lot of harm in going back to living with it.
> fix: Fix performance issue into o2m.addedBeforeLoaded handling.

- packages/integration-tests/src/Entity.test.ts
- packages/orm/src/relations/ManyToManyCollection.ts
- packages/orm/src/relations/ManyToOneReference.ts
- packages/orm/src/relations/OneToManyCollection.ts
Given we can make a ton of o2ms, lazy init fields we don't may not.
Without the lazy init, the `hasMany` is a hot spot:
With the lazy init, it is not:
> fix: Lazy init cascadeDelete and addedBeforeLoaded.

- packages/integration-tests/src/Entity.test.ts
- packages/orm/src/config.ts
- packages/orm/src/index.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
The `hasAsyncPersistedField` cstr constantly converted reactive hints to load hints, which:
a) often were not needed, and
b) will always be the same so can be done once and cached
Before, loading ~5k project items each with ~8-ish derived fields, `convertToLoadHint` was a hot spot:
After, it is not:
> fix: Fix repeatedly converting load hints

- docs/docs/querying/partial-update-apis.md
- packages/integration-tests/src/EntityManager.createOrUpdatePartial.test.ts
- packages/integration-tests/src/toMatchEntity.test.ts
- packages/orm/src/createOrUpdatePartial.ts
- packages/orm/src/index.ts
- packages/test-utils/src/toMatchEntity.ts
The overall semantics of `undefined` in partial APIs is "ignore".
Setting the collection to `null` will still clear it.
> fix: Fix setPartial a collection to undefined should be ignored.

- packages/integration-tests/src/EntityManager.factories.test.ts
- packages/orm/src/newTestInstance.ts
If a polymorphic ref wasn't set, the factory would not look for all existing types of any parent.
> fix: Fix defaults for polys looking for all parent types.

- packages/integration-tests/src/EntityManager.lens.test.ts
- packages/orm/src/BaseEntity.ts
- packages/orm/src/loadLens.ts
loadLens had undefined & soft-deleted filtering that had not been replicated in getLens.
> fix: Fix getLens not filtering undefined references.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/integration-tests/src/entities/Author.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/integration-tests/src/entities/AuthorStatCodegen.ts
- packages/integration-tests/src/entities/BookAdvanceCodegen.ts
- packages/integration-tests/src/entities/BookCodegen.ts
- packages/integration-tests/src/entities/BookReviewCodegen.ts
- packages/integration-tests/src/entities/CommentCodegen.ts
- packages/integration-tests/src/entities/CriticCodegen.ts
- packages/integration-tests/src/entities/CriticColumnCodegen.ts
- packages/integration-tests/src/entities/ImageCodegen.ts
- packages/integration-tests/src/entities/PublisherCodegen.ts
- packages/integration-tests/src/entities/PublisherGroupCodegen.ts
- packages/integration-tests/src/entities/SmallPublisherCodegen.ts
- packages/integration-tests/src/entities/TagCodegen.ts
- packages/tests/schema-misc/src/entities/ArtistCodegen.ts
- packages/tests/schema-misc/src/entities/AuthorCodegen.ts
- packages/tests/schema-misc/src/entities/PaintingCodegen.ts
- packages/tests/untagged-ids/src/entities/AuthorCodegen.ts
- packages/tests/untagged-ids/src/entities/BookCodegen.ts
- packages/tests/uuid-ids/src/entities/AuthorCodegen.ts
- packages/tests/uuid-ids/src/entities/BookCodegen.ts
Because then they're not visible to Reactive hints.
Honestly I forget the rationale for skipping them in the first place, so maybe there is a good reason and I'm not remembering?
> fix: Don't skip derived fields in the FieldsOf type.

- packages/orm/src/QueryBuilder.ts
- packages/orm/src/QueryParser.ts
Since callers may add their own conditions after the fact.
> fix: Allow buildQuery to keep joins.

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/orm/src/Aliases.ts
- packages/orm/src/EntityFilter.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/dataloaders/findDataLoader.ts
I.e. instead of:
```
const b = alias(Book);
em.find(Author, { books: { as: b } });
```
We can bind it directly w/o the `as`:
```
const b = alias(Book);
em.find(Author, { books: b });
```
Granted, this only works for leaf tables; tables that are used for subsequent joins will still use the `as` syntax.
> feat: Allow aliases to be entity filters.

- packages/orm/src/EntityManager.ts
- packages/orm/src/QueryBuilder.ts
- packages/orm/src/dataloaders/lensDataLoader.ts
- packages/orm/src/drivers/Driver.ts
- packages/orm/src/drivers/InMemoryDriver.ts
- packages/orm/src/drivers/PostgresDriver.ts
- packages/orm/src/drivers/buildKnexQuery.ts
- packages/orm/src/drivers/index.ts
This lets lensDataLoader ask the driver to execute its ParsedFindQuery.
PostgresDriver implements the new executeFind method by calling the same QueryBuilder buildQuery function, but now moved/extracted into a dedicated buildKnexQuery file/method.
> chore: Add Driver.executeFind(ParsedFindQuery) method.

- packages/orm/src/index.ts
- packages/orm/src/loadHints.ts
- packages/orm/src/withLoaded.ts
* Added `assertLoaded` that fails if the entity isn't loaded for its hint
* Added `ensureWithLoaded` that returns a `WithLoaded` after calling `assertLoaded` 
* Renamed `ensureLoadedThen` to `maybePopulateThen` as the naming was non-obvious
* Repurposed unused `ensureLoaded` to `assertLoaded` then return its entity
> feat: add assertLoaded 

- packages/integration-tests/src/drivers/Driver.test.tsx
- packages/orm/src/QueryParser.ts
- packages/orm/src/dataloaders/findByUniqueDataLoader.ts
- packages/orm/src/dataloaders/lensDataLoader.ts
- packages/orm/src/dataloaders/oneToManyDataLoader.ts
- packages/orm/src/drivers/Driver.ts
- packages/orm/src/drivers/InMemoryDriver.ts
- packages/orm/src/drivers/PostgresDriver.ts
Now that we have the `ParsedFindQuery` ADT, we can do more in the data loaders and make the drivers more lean.
At first I was thinking it was a good idea the drivers could be "more logical" i.e. execute domain operations like "load this o2m" than dropping down to SQL and parsing SQL.
But given drivers will have to implement `executeFind` anyway, and how simple the ADT is (no real parsing overhead), it seems better to pull this logic back out of drivers.
> feat: Implement oneToManyDataLoader with executeFind.

- packages/codegen/src/generateEnumFile.ts
- packages/integration-tests/src/entities/AdvanceStatus.ts
- packages/integration-tests/src/entities/Color.ts
- packages/integration-tests/src/entities/ImageType.ts
- packages/integration-tests/src/entities/PublisherSize.ts
- packages/integration-tests/src/entities/PublisherType.ts
Allows getting the ids more succinctly, i.e. instead of:
```
PublisherSizes.getByCode(PubliserSize.Small).id;
```
You can now do:
```
PublisherSizeDetails.Small.id;
```
I've gone done the slippery slope of de-`enum`-ing `PublisherSize` before, i.e. to allow just `PublisherSize.Small.id` but that's been too distrupting to existing codebases + various tooling like putting the enums on the wire for GraphQL/JSON/etc.
> feat: Generate a const for enum details.

- packages/orm/src/drivers/PostgresDriver.ts
> fix: Fix DELETEs bumping oplocks for UPDATEs.

- docs/docs/features/loading-entities.md
- docs/docs/testing/entity-matcher.md
Made two updates to doc:
* Added a note that `joist-test-utils` is a separate package that needs to be installed to use the test helpers. Fixed a type in the example. 
* Fixed some typos (Kelsey -> Kysely) and grammar in the docs.
> docs: Updates to Docs

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/orm/src/EntityFilter.ts
This makes it a suitable substition for FilterOf<Author> when you also want to include an `as: a` alias binding.
> fix: Provide default generics for EntityFilter.

- packages/graphql-resolver-utils/src/entityResolver.ts
This optimizes GraphQL queries like:
```graphql
query {
books {
author {
id
}
}
}
```
To not load the `Author` entities since we know we're only returning their `id`, which the `Book` entities already have in memory from their `books.author_id` FK column.
Currently we only apply this optimization to m2o's, where we have the FK value immediately available in memory.
We can't really do the same optimization for o2o or o2m, b/c both of those fundamentally require making a database call to find "what's on the other side", at which point we may as well bring back the full entity anyway (vs. an IMO micro-optimization like bringing back only the id ... granted, we could do this someday as well, but it's not for-free as this initial m2o one).
> feat: Optimize returning only m2o ids.

- packages/integration-tests/src/EntityManager.find.batch.test.ts
- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/relations/CustomReference.test.ts
- packages/integration-tests/src/relations/OneToManyCollection.test.ts
- packages/integration-tests/src/relations/OneToOneReference.test.ts
- packages/integration-tests/src/relations/hasManyDerived.test.ts
- packages/orm/src/Aliases.ts
- packages/orm/src/EntityFilter.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/dataloaders/findByUniqueDataLoader.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/dataloaders/lensDataLoader.ts
- packages/orm/src/dataloaders/loadDataLoader.ts
- packages/orm/src/dataloaders/manyToManyDataLoader.ts
- packages/orm/src/dataloaders/manyToManyFindDataLoader.ts
- packages/orm/src/dataloaders/oneToManyDataLoader.ts
- packages/orm/src/dataloaders/oneToManyFindDataLoader.ts
- packages/orm/src/dataloaders/oneToOneDataLoader.ts
- packages/orm/src/drivers/Driver.ts
- packages/orm/src/drivers/IdAssigner.ts
- packages/orm/src/drivers/InMemoryDriver.ts
- packages/orm/src/drivers/PostgresDriver.ts
- packages/orm/src/utils.ts
This PR changes Joist's "auto-batch em.find/SELECT queries" from using UNION ALLs to a CTE of VALUES.
Previously Joist would batch two `em.find`s into a single SQL query that the two potentially random queries (other than being for the same entity) stitched together with a `UNION ALL`:
```sql
(select *, -1 as __tag, -1 as __row from "authors" where "id" = $1)
union all (select "a".*, 0 as __tag, row_number() over () as __row from "authors" as "a" where "a"."id" = $2 order by "a"."id" ASC, "a"."id" asc limit $3)
union all (select "a".*, 1 as __tag, row_number() over () as __row from "authors" as "a" where "a"."id" = $4 order by "a"."age" DESC, "a"."id" asc limit $5) order by "__tag" asc",
```
The `__tag` syntax was used to tell which `em.find` a returned row belonged two, i.e. if we had …
> feat: Use CTEs instead of UNIONs to batch queries. 

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/dataloaders/findCountDataLoader.ts
Using the dataloader infra even though we're not technically batching the queries together.
Also make "count all" handling cute by adjusting the count up/down based on WIP changes.
> feat: Add EntityManager-level caching for em.findCount.

- packages/integration-tests/src/run.test.ts
- packages/test-utils/src/run.ts
Granted, we're assuming POJOs won't have cycles (vs. a true already visited cache), but that seems fine for now.
> fix: Fix gatherEntities looping on cycles.

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/integration-tests/src/entities/inserts.ts
- packages/orm/src/Aliases.ts
- packages/orm/src/QueryParser.ts
Only eq, ne, and in, just as in `em.find` inline conditions.
> fix: Support for polys in aliases.

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/dataloaders/findOrCreateDataLoader.ts
Previously if em.findOrCreate was called in a loop, and two loop iterations asked to create the same entity, we would create it twice, leading to things like unique constraint failures.
We now use dataloader, not specifically for batching, but just for deduping, as dataloader's cache key will recognize two loop iterations asking for the same promise.
Note that we still expect the 1st `where` parameter to be the same across iterations of the loop, i.e. if one loop does findOrCreate with { firstName: "a1" } but the next loop iteration changes to do findOrCreate { lastName: "a2" } then we're currently not attempting to do anything intelligent for that.
Which should be fine; most loop iterations should use an effectively stable/hard-coded set of conditions (albeit with different values, which …
> feat: Dedupe em.findOrCreates that are called in a loop.

- packages/codegen/package.json
- packages/codegen/src/EntityDbMetadata.ts
- packages/migration-utils/package.json
- packages/tests/schema-misc/migrations/1580658856631_author.js
- yarn.lock
We assume DEFERRABLE and INITIALLY DEFERRED fks, which are both somewhat esoteric/non-default features, so warn users about them.
> feat: Warn on misconfigured foreign keys.

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/drivers/EntityWriter.ts
- packages/orm/src/drivers/PostgresDriver.ts
This provides the same decoupling from Knex that the QueryParser did for finds.
> feat: Add Ops AST/EntityWriter for writes

- docs/package.json
- package.json
- packages/codegen/package.json
- packages/graphql-codegen/package.json
- packages/graphql-codegen/src/utils.ts
- packages/graphql-resolver-utils/package.json
- packages/integration-tests/package.json
- packages/integration-tests/src/Entity.test.ts
- packages/migration-utils/package.json
- packages/orm/package.json
- packages/orm/src/config.ts
- packages/test-utils/package.json
- packages/tests/schema-misc/package.json
- packages/tests/untagged-ids/package.json
- packages/tests/uuid-ids/package.json
- packages/utils/package.json
- yarn.lock
Marking as a feature to force a release.
Not using the `const` feature yet.
This shouldn't force downstream projects to use TypeScript 5.x.
> feat: Bump TypeScript, misc deps.

- packages/codegen/src/EntityDbMetadata.ts
~~I've noticed this isn't supported downstream in ts-poet. I'll leave this as a draft revisit this once I've had a look at that. This is assuming a double `@@` is the way to go.~~
----
As mentioned in #676, the import logic of `superstructType` and `userFieldTypeType` splits on `@` and uses the first two parts. This causes issues when importing from a namespaced package.
```json
{ "fields": { "address": { "superstruct": "address@@company/common" } } }
```
results in the reconstructed import passed to ts-poet `address@`.
This PR rests all of the following parts and joins them back up with an `@`.
> fix: Add support namespaced packages within config imports

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/orm/src/EntityFilter.ts
- packages/orm/src/QueryParser.ts
I think personally I would prefer not allowing relations to be used in find filters, however b/c ManyToOneReference.id makes it structurally match the EntityFilter, it seems hard/not worth the complexity to prevent the ManyToOneReference in the EntityFilter mapped type as a compile error (which would be ideal imo).
So instead just suppose m2os by calling `.id`.
> fix: Allow m2os to be used in filters. Fixes #680.

- packages/codegen/src/generateMetadataFile.ts
- packages/codegen/src/symbols.ts
- packages/integration-tests/joist-config.json
- packages/integration-tests/migrations/1580658856631_author.ts
- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/integration-tests/src/entities/inserts.ts
- packages/integration-tests/src/entities/metadata.ts
- packages/integration-tests/src/entities/types.ts
- packages/orm/src/serde.ts
As discussed in #684, stringifies within SuperstructSerde and a newly introduced JsonSerde.
Will see how this behaves in ~~GHA~~ circleci, but locally I'm getting
```
● EntityManager › findOrCreate resolves dups with different where clauses in a loop
expect(received).toBe(expected) // Object.is equality
Expected: "C"
Received: "B"
891 |     expect(a1).toEqual(a2);
892 |     // And the last upsert wins
> 893 |     expect(a1.lastName).toBe("C");
|                         ^
894 |   });
895 |
896 |   it("can find and populate with findOrCreate", async () => {
at Object.toBe (src/EntityManager.test.ts:893:25)
```
which is curious because I'm not sure where my changes are coming in to play here.
> fix: jsonb top level array

- packages/codegen/src/generateMetadataFile.ts
- packages/integration-tests/migrations/1580658856631_author.ts
- packages/integration-tests/src/entities/AuthorStatCodegen.ts
- packages/integration-tests/src/entities/metadata.ts
I introduced an issue within #685 passing the wrong amount of args in to JsonSerde in the codegen, resulting in ts issues in any generated `metadata.ts` for any jsonb columns with no `superstruct` config.
There are no usages of non-superstruct'd json within the integration tests as far as I could tell, which would have caught this, so I've added in a json column to `author_stats` which looked like a good place for this, but let me know!
Sorry about that!
> fix: JsonSerde args within codegen

- packages/integration-tests/src/rules.test.ts
- packages/orm/src/rules.ts
Following on from https://github.com/stephenh/joist-ts/discussions/692.
- ValidationErrors holds a property of entities which have circular references.
- Jest returns the failure error of a test back to its root process by stringifying
- Jest also clones the returned object before stringifying, destroying the prototype where a toJSON method would live
This (from my testing, Jest 29.5.0 w/ Circus) _should_ stop issues around circular references by introducing toJSON as a property of ValidationErrors which survives the clone. 
I've added in a test to attempt to represent this issue, wasn't sure the best place for it - happy to move/change.
> fix: add toJSON to ValidationErrors

- docs/docs/features/entity-manager.md
- docs/docs/features/queries-find.md
- docs/docs/getting-started/configuration.md
- docs/docs/modeling/jsonb-fields.md
We've been working with Joist for the last couple of weeks now and speaking to my team wanted to see what they thought is missing or could be improved with the docs while it's all still fresh and new.
- Add `zodSchema` & `type` to FieldConfig under Configuration
- Add `Zod` to the JSONB Fields page alongside Superstruct
- Mention missing operators "Find Queries"
- Add some explain some addtional semantics around find/findOne/load etc; if they throw, what they throw etc
- Not entirely happy with the formatting of this, so open to ideas
Bit of a sidenote, but I was suprised to see that `load` just throws a generic base Error and not something from Joist, NotFoundError or otherwise.
> docs: zod + type + em method semantics

- packages/integration-tests/src/EntityManager.queries.test.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/orm/src/EntityFilter.ts
- packages/orm/src/QueryParser.ts
One of the things I hit early on was not realising each ExpressionFilter needs an `and` or an `or` but not both. TypeScript doesn't catch this with it's union/object handling.
I've added in never to the other side of expressions to ensure TS does catch this:
```ts
/** Filters against complex expressions of filters. */
export type ExpressionFilter = (
| { and: Array<ExpressionFilter | ColumnCondition | undefined>; or?: never }
| { or: Array<ExpressionFilter | ColumnCondition | undefined>; and?: never }
) & { pruneIfUndefined?: "any" | "all" };
```
It doesn't result in the best error, but it at least helps point to the fact joist isn't going to support this:
> fix: ensure exclusive `or` or `and` in ExpressionFilter

- packages/orm/src/EntityManager.ts
I would imagine this is backwards compatiable as NotFoundError is a sub type of Error.
> feat: use NotFoundError in load & loadAll

- packages/orm/src/newTestInstance.ts
Skipping an integration test, but locally I made Author.mentor required and verified that it works.
Granted, making this work for a non-pg / non-sequence database is going to suck.
Fixes #702
> fix: Don't infinite recurse on required self-ref keys.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/integration-tests/src/entities/AuthorCodegen.ts
- packages/integration-tests/src/entities/AuthorStatCodegen.ts
- packages/integration-tests/src/entities/BookAdvanceCodegen.ts
- packages/integration-tests/src/entities/BookCodegen.ts
- packages/integration-tests/src/entities/BookReviewCodegen.ts
- packages/integration-tests/src/entities/CommentCodegen.ts
- packages/integration-tests/src/entities/CriticCodegen.ts
- packages/integration-tests/src/entities/CriticColumnCodegen.ts
- packages/integration-tests/src/entities/ImageCodegen.ts
- packages/integration-tests/src/entities/LargePublisherCodegen.ts
- packages/integration-tests/src/entities/PublisherCodegen.ts
- packages/integration-tests/src/entities/PublisherGroupCodegen.ts
- packages/integration-tests/src/entities/SmallPublisherCodegen.ts
- packages/integration-tests/src/entities/TagCodegen.ts
- packages/integration-tests/src/entities/UserCodegen.ts
- packages/tests/schema-misc/src/entities/ArtistCodegen.ts
- packages/tests/schema-misc/src/entities/AuthorCodegen.ts
- packages/tests/schema-misc/src/entities/BookCodegen.ts
- packages/tests/schema-misc/src/entities/DatabaseOwnerCodegen.ts
- packages/tests/schema-misc/src/entities/PaintingCodegen.ts
- packages/tests/untagged-ids/src/entities/AuthorCodegen.ts
- packages/tests/untagged-ids/src/entities/BookCodegen.ts
- packages/tests/uuid-ids/src/entities/AuthorCodegen.ts
- packages/tests/uuid-ids/src/entities/BookCodegen.ts
Allows using code generated ID types generically.  eg,
```typescript
type Foo<T> = T extends { _type?: infer U } ? U : never;
const a: Foo<AuthorId> = em.create(Author, ...); // works
const b: Foo<AuthorId> = em.create(Book, ...); // error: Type 'Book' is not assignable to type 'Author'
```
> feat: Updated EntityId codegen to use actual type instead of a string

- docs/docs/modeling/relations.md
Adding documentation for some things that caught me up in the beginning of using Joist.  Especially coming from a Rails background. 
Looks like some trailing whitespace was automatically deleted too.
> fix(docs): Adding documentation about how to check for the presence of relations and get relation ids.

- packages/integration-tests/src/entities/Book.test.ts
- packages/integration-tests/src/entities/Book.ts
- packages/integration-tests/src/getProperties.test.ts
- packages/orm/src/EntityManager.ts
We disconnect deleted entities from the rest of the object graph, to ensure the most accurate/consistent view of the graph.
However, if we disconnect deleted entities too soon, i.e. before their own hooks run, then their beforeDeletes cannot really do meaningful logic like custom cascade deletes.
I'd considered just not disconnecting the entities at all, because our o2m/m2o get's now "filter deleted entities" logic, but turns out the disconnection also has the purposeful (at least documented by tests) side-effect by un-setting optional FKs that were pointing to the deleted entity.
And so if we just stop doing the disconnect, this side effect never happens (i.e. unsetting the optional `Author.publisher` field when a Publisher is deleted).
So this PR moves where we invoke `beforeDelete`, to …
> fix: Run beforeDelete hooks before entities are disconnected.

- packages/integration-tests/src/Inheritance.test.ts
- packages/orm/src/QueryParser.ts
All order by properties which existed in `meta.allFields` were built against the root alias, rather than the base type table the field belonged to.
- Added repro
- Looks like aliasPrefix is the cleanest way to do this, but haven't been around QueryParser too much yet!
> fix: orderBy on cti base fields 

- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/relations/ManyToManyCollection.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/dataloaders/findCountDataLoader.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/dataloaders/manyToManyDataLoader.ts
- packages/orm/src/index.ts
- packages/orm/src/relations/ManyToManyCollection.ts
- packages/orm/src/relations/ManyToOneReference.ts
- packages/orm/src/relations/OneToManyCollection.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
- packages/orm/src/relations/hasPersistedAsyncReference.ts
Potential alternatives:
1. Current version, which is `#` private fields, exposed via a separate `__api` object
2. Stay with TS private fields, and have `getEmInternalApi` just return `em` directly casted, b/c the field names line up and callable, i.e.:
```
interface InternalApi {
someField: string;
}
class Foo {
private someField: string;
}
function getInternalApi(foo: Foo) {
return foo as InternalApi;
}
```
> chore: Clean up EntityManager's private fields.

- packages/integration-tests/src/Entity.test.ts
- packages/integration-tests/src/EntityManager.reactiveRules.test.tsx
- packages/integration-tests/src/EntityManager.test.ts
- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/Author.ts
- packages/integration-tests/src/getProperties.test.ts
- packages/orm/src/getProperties.ts
- packages/orm/src/reactiveHints.ts
This conventionalizes having `transientFields` that Reacted logic is allowed to access.
This is generally similar to going through `fullNonReactiveAccess`, but:
1. Is less scary that `fullNonReactiveAccess`
2. Provides an alternative to `fullNonReactiveAccess` to avoid normalizing usage of `fNRA`
3. Highlights that transient fields are not columns/fields in the db
> feat: Add transientFields convention to Reacted.

- packages/integration-tests/src/entities/Book.ts
- packages/orm/src/changes.ts
- packages/orm/src/reactiveHints.ts
This allows validation rules to check if fields have been explicitly updated or changed without going through fullNonReactiveAccess.
Fixes #743
> feat: Add changes field to Reacted.

- packages/orm/src/ReactionsManager.ts
This doesn't strictly fix anything, but is a good optimization.
> fix: Dedupe relations before calling load.

- packages/integration-tests/src/entities/Author.test.ts
- packages/integration-tests/src/entities/BookReview.ts
- packages/integration-tests/src/relations/PersistedAsyncProperty.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/loadHints.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
This prevents 'scopeUpdated has not been derived yet' errors, when we've created a new entity, and some dependent field depends on a field within the new entity.
Note that we're careful to only call `.load()` on derived fields that are explicitly new/not set yet, as otherwise we'd defeat the purpose of "derived fields can depend on other derived fields to cheaply calculate their values".
> fix: Transitively load derived values when the entities are new.

- packages/integration-tests/src/EntityManager.populate.test.ts
- packages/integration-tests/src/reactiveHints.test.ts
- packages/integration-tests/src/relations/PersistedAsyncProperty.test.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/reactiveHints.ts
- packages/orm/src/relations/hasPersistedAsyncProperty.ts
A previous fix allowed derived fields to .load() their dependencies,
i.e. if those dependencies were themselves new and not yet calced.
However, it did that conditionally, i.e. if the dependency was already
calced, it would not re-calc it. Which is the desired behavior, to avoid
re-calculating a whole tree of derived values unnecessary.
That said, it broke that explicit `.populate` calls are the programmer
requesting a fresh calc, i.e. where they know they've recently mutated
the graph, so this PR restores the behavior.
> fix: Fix derived field populate

- packages/integration-tests/src/EntityManager.test.ts
- packages/orm/src/BaseEntity.ts
Observed the below behaviour when serialising CTI entities with toJSON, of skipping fields of the parent class:
On the assumption that this isn't the desired behaviour:
* Added a test case to repro + catch this
* Updated the toJSON function to use metadata.allFields instead of metadata.fields
> fix: CTI BaseEntity.toJSON skipping parent fields

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/generate.ts
- packages/codegen/src/index.ts
- packages/graphql-codegen/src/testUtils.ts
A continuation / rework of: https://github.com/stephenh/joist-ts/pull/777
Summary: 
* Move to a console.warn for the warning around the FK not being deferred
* Crash with a non-zero exit code if any entities are deemed invalid for having an non-deferred FK
* In this case also insert a throw within `metadata.ts` to ensure the generated code won't run in an unsafe manner despite the codegen throw
> feat: Codegen - Delayed throw on non-deferred FK Found

- packages/integration-tests/src/toMatchEntity.test.ts
- packages/test-utils/src/toMatchEntity.ts
This basically totally rewrites `toMatchEntity` to be less adhoc/hacky, and instead step back and think about what it's really doing.
See in-source comments that describe how we use `expected` as a template to create our own copy of `actual`, to avoid Jest infinitely recursing into connection pools, but then also still handle entities being in either `expected` or `actual` as "terminal" values the user wants to assert against.
> fix: Fix toMatchEntity failing with pojos.

- packages/integration-tests/src/EntityManager.find.batch.test.ts
- packages/integration-tests/src/EntityManager.lens.test.ts
- packages/integration-tests/src/QueryParser.quotes.test.ts
- packages/orm/src/drivers/buildKnexQuery.ts
Not sure on the best place for this, as it relies on both metadata + parseFindQuery and Knex's internals.
> fix: Fix double quoting in buildKnexQuery

- packages/integration-tests/src/EntityManager.ctiQueries.test.ts
- packages/integration-tests/src/entities/metadata.ts
- packages/integration-tests/src/testDrivers.ts
- packages/orm/src/Aliases.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/index.ts
Getting up some cases here to show the problem - can move them somewhere more appropriate once the fix is in - it's the last two.
Essentially it looks like complex filtering don't take in to account that they might be filtering on the parent table.
See how a complex condition (using either the Publisher or SmallPublisher as the alias) against `name`, which exists on the publisher table, has the filter condition's alias set to `sp` - i.e the child table.
```js
{
selects: [ 'sp.*', 'sp_b0.*', 'sp.id as id' ],
tables: [
{ alias: 'sp', table: 'small_publishers', join: 'primary' },
{
alias: 'sp_b0',
table: 'publishers',
join: 'outer',
col1: 'sp.id',
col2: 'sp_b0.id',
distinct: false
}
],
conditions: [],
orderBys: [ { alias: 'sp', column: 'id', order: 'ASC' } ],
complexConditions: [
{
op: …
```
> fix: complex filters on cti of parent fields do not filter to correct table

- packages/codegen/src/generate.ts
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/entities/metadata.ts
- packages/tests/number-ids/src/entities/metadata.ts
- packages/tests/schema-misc/src/entities/metadata.ts
- packages/tests/untagged-ids/src/entities/metadata.ts
- packages/tests/uuid-ids/src/entities/metadata.ts
And then work it into the app-specific EntityManager as well.
Hopefully this will mitigate some of the "ids are now numbers or strings?!" fallout from the last Joist release, which added support for number-typed ids.
> feat: Generate an app-specific Entity type.

- packages/codegen/src/generate.ts
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/graphql-resolver-utils/src/saveEntity.ts
- packages/orm/src/BaseEntity.ts
- packages/orm/src/Entity.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/EntityMetadata.ts
- packages/orm/src/createOrUpdatePartial.ts
- packages/orm/src/index.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/EntityManager.test.ts
- packages/tests/integration/src/entities/metadata.ts
- packages/tests/integration/src/resolvers/mutations/utils.ts
- packages/tests/integration/src/setupDbTests.ts
- packages/tests/number-ids/src/entities/metadata.ts
- packages/tests/schema-misc/src/entities/metadata.ts
- packages/tests/untagged-ids/src/entities/metadata.ts
- packages/tests/uuid-ids/src/entities/metadata.ts
This extends our existing convention of an "application-specific `EntityManager`" (which is the EntityManager but bound/narrowed to your application's specific `Context` / `em.ctx` object), to an "application-specific `Entity`", that will have the `id` / `idMaybe` fields narrowed to "just string" or "just number" based on your `joist-config.json`'s `idType` setting.
This should give us the best of both worlds:
* Joist core is agnostic about `id: string | number` (and if anything these PRs have caught/enforced stragglers still treating `entity.id` as a tagged id), but
* Applications get their preferred `id: string` or `id: number`.
The cost is admittedly some increased complexity:
* The `EntityManager` itself is now typed on the application's narrowed `Entity`
* Applications generally need …
> feat: Reroll per-application Entity

- packages/graphql-resolver-utils/src/hint.ts
- packages/tests/integration/src/entityResolver.test.ts
The args could be a filter that loads substantially less/different data than the relation, so we'll defer to the user's custom resolver to do its custom logic.
> fix: Don't populate relations if there are args.

- packages/orm/src/dataloaders/findOrCreateDataLoader.ts
- packages/tests/integration/src/EntityManager.test.ts
The API for findOrCreate is opts-based, so wants `publisher: undefined`, which matches Joist's opinionated choice of `undefined` to represent empty within the object graph.
But when we call `em.find`, it drops `publisher: undefined` due to a legacy-but-valid desire to match the behavior of `em.findGql` where it's very easy for a resolver implementation that handles "the client didn't include a filter for publisherId" to accidentally include the `publisher` key on the `em.find` call.
I.e. something like:
```
const { publisherId } = filter;
await em.find(..., { publisherId });
```
Is the destructuring/restructuring idiom that looks innocent but will mean the `publisherId` key is always set on the `em.find` call, regardless of being included in the incoming filter.
Anyway, this watches for …
> fix: Fix findOrCreate with undefined.

- packages/orm/src/ReactionsManager.ts
- packages/orm/src/relations/OneToManyCollection.ts
- packages/orm/src/relations/PersistedAsyncProperty.ts
- packages/orm/src/relations/PersistedAsyncReference.ts
- packages/plugins/join-preloading/src/partitionHint.ts
- packages/tests/integration/src/Entity.test.ts
- packages/tests/integration/src/EntityManager.joins.test.ts
- packages/tests/integration/src/EntityManager.reactiveRules.test.tsx
- packages/tests/integration/src/entities/Author.ts
- packages/tests/integration/src/entities/BookReview.ts
- packages/tests/integration/src/relations/OneToManyCollection.test.ts
- packages/tests/integration/src/relations/PersistedAsyncProperty.test.ts
- packages/tests/integration/src/relations/PersistedAsyncReference.test.ts
The `isLoaded` & `load` methods for PersistedAsyncProperty & Reference now will automatically re-load if their load hint drifts to a non-fully-loaded state.
We still keep the `loaded` fields to know if we've ever been loaded, and avoid `.get` accidentally regressing from a "load hint loaded, returning correct values" to "load hint becomes unloaded, starts returning old previously calculated value".
I.e. once a persisted property has been loaded, we want it to re-load, but we don't want it to fallback on old values.
We achieve this by:
* `isLoaded` always checks the load hint
* `load` always checks `isLoaded` (not the previous `#loaded` field)
* `get` checks `#loaded` to make sure it doesn't revert
> fix: Fix reactions recalculating after graph mutations.

- packages/orm/src/relations/CustomCollection.ts
- packages/orm/src/relations/CustomReference.ts
- packages/tests/integration/src/Entity.test.ts
- packages/tests/integration/src/entities/Image.ts
- packages/tests/integration/src/entities/Publisher.ts
- packages/tests/integration/src/relations/hasManyDerived.test.ts
- packages/tests/integration/src/relations/hasOneDerived.test.ts
Removing some more instances of cached `_isLoaded: boolean` fields becoming stale due to graph changes and actually checking instead.
> fix: Really check if relations are loaded for CustomCollection and CustomReference

- packages/graphql-codegen/src/generateEnumsGraphql.ts
Adds a combined `AllEnumDetails` type to the `enums.graphl` codegen to make it easier to create a query resolver that can return the "details" of any enum
```graphql
type AllEnumDetails {
enumFoo: [FooDetail!]! 
enumBar: [BarDetail!]! 
}
```
> feat: Add AllEnumDetails to graphql codegen

- hydrate-perf.mkd
- packages/orm/package.json
- packages/utils/src/connection.ts
- packages/utils/src/index.ts
- packages/utils/src/setupLatestPgTypes.ts
- yarn.lock
Before `parseDate` was ~40% of the time:
Afterwards it's ~25%
> feat: Use the latest pg-types for a timestamp perf fix.

- packages/orm/src/relations/ManyToManyCollection.ts
- packages/tests/integration/src/relations/ManyToManyCollection.test.ts
This matches how our other relation `get`s work.
> fix: Change m2m.get ensureNotDeleted to ignore pending.

- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/Entity.test.ts
- packages/tests/integration/src/EntityManager.test.ts
- packages/tests/integration/src/entities/Author.ts
- packages/tests/integration/src/relations/PersistedAsyncProperty.test.ts
Previously, `em.touch` did four things:
1. Bump updatedAt (if available)
2. Run hooks
3. Recalc all reactive derived fields
4. Revalidate all reactive rules
We have an issue in production where we're using em.touch to bump updatedAt's up a tree (i.e. child changes, bump parent) for history purposes.
However, the parent has an unrelated validation rule that validly fails, i.e. the parent entity was valid in the past, but unrelated changes have made one of its rules become invalid (because we purposefully side-stepped the rule's reactivity).
(Specifically, the parent entity is a PRPC that now has an invalid lot configuration, because new option dependencies/constraints had been added; which is fine, but the configuration should only be fixed the next time the users change/update the config, …
> feat: Add em.recalc, simplify em.touch.

- packages/orm/src/ReactionsManager.ts
- packages/orm/src/reactiveHints.ts
- packages/orm/src/relations/ManyToManyCollection.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/EntityManager.reactiveRules.test.tsx
- packages/tests/integration/src/reactiveHints.test.ts
- packages/tests/integration/src/relations/ManyToManyCollection.test.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
If we had:
* Books <- m2m -> Tags
* Author.tagsOfAllBooks watching `books: "tags"`
* And `a1 / b1.tags = [t1]` was an existing b1/tag
* When we added `b2.tags.add(1)` this correctly recalc'd `b2 -> a2`, `a2.tagsOfAllBooks`
* But it also walked from `t1.books.authors` and found `a1` and `a2`
This was unnecessary, because b1.tags hadn't changed.
> fix: Fix m2m over reactivity

- packages/orm/src/QueryParser.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/entities/inserts.ts
Originally the QueryParser/poly handling code could only do ANDs, which was fine for "IS NULL" checks, but couldn't also do "OR"s.
A recent-ish refactoring of QueryParser added inlineExpressions (optional ORs), in addition to the inlineConditions (ANDs), so this is easy/able to implement now.
> fix: Implement not null checks on polymorphic references.

- packages/orm/src/drivers/buildKnexQuery.ts
Fixes the `nin` condition within `buildKnexQuery` to use `all()` rather than `any()` which for `nin` entirely permissive.
This is inline with findDataLoader's `makeOp`: https://github.com/stephenh/joist-ts/blob/8960c68ae54cbe0f9d5907ad4aac5520d8383fa5/packages/orm/src/dataloaders/findDataLoader.ts#L271
> fix: nin any -> all operator in `buildKnexQuery`

- packages/codegen/src/index.ts
- packages/codegen/src/utils.ts
The pg-structure bumps requires us to load all schemas, so that our cyanaudit triggers don't blow up the pg-structure load metadata step.
> fix: Avoid failing on cross-schema triggers.

- packages/orm/src/Aliases.ts
- packages/orm/src/EntityFilter.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/QueryVisitor.ts
- packages/orm/src/dataloaders/findByUniqueDataLoader.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/dataloaders/lensDataLoader.ts
- packages/orm/src/dataloaders/loadDataLoader.ts
- packages/orm/src/dataloaders/manyToManyDataLoader.ts
- packages/orm/src/dataloaders/manyToManyFindDataLoader.ts
- packages/orm/src/dataloaders/oneToManyDataLoader.ts
- packages/orm/src/dataloaders/oneToManyFindDataLoader.ts
- packages/orm/src/dataloaders/oneToOneDataLoader.ts
- packages/orm/src/dataloaders/populateDataLoader.ts
- packages/orm/src/drivers/buildKnexQuery.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
Aliases can accept other aliases:
```ts
const em = newEntityManager();
const [a, b] = aliases(Author, Book);
const books = await em.find(
Book,
{ as: b, author: a },
{ conditions: { and: [a.id.eq(b.id)] }
});
```
Fixes #793.
> feat: Support filtering on other columns.

- packages/orm/src/QueryParser.ts
- packages/orm/src/createOrUpdatePartial.ts
- packages/orm/src/utils.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/EntityManager.createOrUpdatePartial.test.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
Calling `setOpts(...)` with a o2o requires the o2o to be loaded, much like setting o2m collections.
However we weren't checking for o2os in the `createOrUpdatePartial` code that partitions out opts from "primitives / relations".
> fix: Fix not loading o2os in createOrUpdatePartial.

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/config.ts
- packages/tests/integration/joist-config.json
Within joist-config.json, configurating references had ended up in the "fields" section, which they are kind of fields, but they are more so relations, so them them there.
This one doesn't have a codemod, but users should see the warning of "unrecognized config" and hopefully will move their FK field config over into relations.
> fix: Move ReactiveRelation config into relations.

- packages/graphql-resolver-utils/src/entityResolver.ts
- packages/tests/integration/src/generated/graphql-types.ts
The check for `Relation<T, ...` where T was a subtype was too strict, because the relation from the base of like `Relation<Publisher, ...>` didn't match the `extends Relation<SmallPublisher, ...>`.
The first generic doesn't actually matter for these checks, so we can `any` it.
> fix: Let entityResolver pick up base type relations.

- packages/orm/src/BaseEntity.ts
- packages/orm/src/Entity.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/Todo.ts
- packages/orm/src/dataloaders/loadDataLoader.ts
- packages/orm/src/drivers/EntityWriter.ts
- packages/orm/src/fields.ts
- packages/orm/src/index.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/EntityManager.test.ts
- packages/tests/integration/src/entities/Author.test.ts
- packages/tests/integration/src/entities/Publisher.ts
- packages/tests/integration/src/entities/codegen/metadata.ts
- packages/tests/integration/src/relations/OneToManyCollection.test.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
With the introduction of ReactiveQueryFields, the `em.flush` method basically needs it's "own dirty tracking", such that after we've done the 1st "micro-flush" (new term) to INSERT/UPDATE the entities, and then detect an RQF needs recalced we need to:
* Reset our "internal dirty state" on all of the just-flushed changes, but
* Preseve the "external dirty state" until the very end of em.flush, i.e. after `beforeCommit` hooks run.
Such that, after calling the RQF.recalc we can tell:
* What, if anything, has actually changed in this 2nd micro-flush loop, vs. the 1st micro-flush loop (i.e. in our internal dirty state), but
* External observation, i.e. hooks like `beforeCommit`, that are not called until *all micro-flushes have finished*, can tell what the flush-wide changed/state was (i.e. …
> fix: Preserve changed/new state for beforeCommit w/RQFs.

- packages/orm/src/serde.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/relations/PolymorphicReference.test.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
If a poly pointed to a subtype (i.e. `task_old`), it's `comp.otherMeta()` would correctly return `TaskOld`.
However the cstr from the `t:1` id would be just `Task`.
So the poly comp would think "this id is not mine", and return null.
So, we want to check the id cstr against the base meta...
...unless this poly does actually have different subtypes from the same base type as separate components/columns, which seems a little odd, but we have a test case covering, so it must have come up in the past.
> fix: Fix polys being too strict on the subtype matching.

- packages/orm/src/reactiveHints.ts
- packages/orm/src/relations/ReactiveGetter.ts
- packages/orm/src/relations/index.ts
- packages/tests/integration/src/Entity.test.ts
- packages/tests/integration/src/entities/Author.ts
- packages/tests/integration/src/relations/ReactiveGetter.test.ts
These provide a way to have dumb/simple/always-get-able getters, but still denote/advertise the underlying primitive fields that are being used, so that the reactivity infra can setup dependency tracking appropriately.
Fixes #1007
> feat: Add ReactiveGetters.

- packages/codegen/package.json
- packages/migration-utils/package.json
- packages/orm/package.json
- packages/orm/src/QueryParser.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/migrations/1580658856631_author.ts
- packages/tests/integration/schema/.history.json
- packages/tests/integration/schema/largePublisher.graphql
- packages/tests/integration/schema/smallPublisher.graphql
- packages/tests/integration/src/EntityManager.find.batch.test.ts
- packages/tests/integration/src/EntityManager.lens.test.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/EntityManager.test.ts
- packages/tests/integration/src/Inheritance.test.ts
- packages/tests/integration/src/entities/codegen/LargePublisherCodegen.ts
- packages/tests/integration/src/entities/codegen/SmallPublisherCodegen.ts
- packages/tests/integration/src/entities/codegen/metadata.ts
- packages/tests/integration/src/entities/inserts.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
- packages/utils/package.json
- yarn.lock
A recent pg bug fix means the last-selected column is what is returned, instead of the last-not-null column which was a pretty convenient "implicit coalesce" that we had been unwittingly relying on.
Fixes #1019.
> fix: Fix columns shared across CTI subtypes.

- packages/orm/src/config.ts
- packages/tests/integration/src/entities/Book.ts
Somewhat optimistically, the setDefault lambda uses ReactiveHints so that maybe we can do cross-default field precedence detection someday.
Which is cool, but it means the lambdas return Reacted<...> instead of the pure entity, so add a fix + coverage for that behavior.
Fixes #1018.
> fix: Update setDefault to allow returning a Reacted entity.

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/tests/esm-misc/joist-config.json
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/entities/codegen/AdminUserCodegen.ts
- packages/tests/integration/src/entities/codegen/LargePublisherCodegen.ts
- packages/tests/integration/src/entities/codegen/SmallPublisherCodegen.ts
- packages/tests/integration/src/entities/codegen/TaskNewCodegen.ts
- packages/tests/integration/src/entities/codegen/TaskOldCodegen.ts
- packages/tests/integration/src/entities/codegen/UserCodegen.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
When I have more time I'll look in to expanding out the esm test dir to catch these;
This PR follows up on #1029 with some rarer usages I missed but hit when running in our app.
These are namely:
- user defined types in FieldConfig
- subtype 'extends' - such as `interface SmallPublisherFields extends from PublisherFields`
I've validated these changes our our app through a patch, but we're not using all functionality of joist, so no promises this is everything. We're using zod, types and CTI though, so decent coverage.
Sorry for the hotfix!
> fix: additional missing type imports

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/generateMetadataFile.ts
- packages/tests/esm-misc/joist-config.json
- packages/tests/esm-misc/src/entities/codegen/metadata.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/entities/codegen/metadata.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/number-ids/src/entities/codegen/metadata.ts
- packages/tests/schema-misc/joist-config.json
- packages/tests/schema-misc/src/entities/codegen/metadata.ts
- packages/tests/untagged-ids/joist-config.json
- packages/tests/untagged-ids/src/entities/codegen/metadata.ts
- packages/tests/uuid-ids/joist-config.json
- packages/tests/uuid-ids/src/entities/codegen/metadata.ts
Bit of trial and error here but looks as if I've figured out a fix for #1031 but lmk if I'm missing something big here!
1. This directly imports entities (their codefile directly rather than via entities.ts) within metadata.ts
2. This does not touch imports to entities elsewhere (such as in *Codegen.ts file, which does trigger circ issues)
3. This is enabled by default, but happy to update this PR to gate this under the esm option
4. Currently not tested as top level await is esm only so perhaps need to expand the esm dir in the future
- Applied this patch in our app and we're running once again, tests passing
There's codegen consequences of this but I haven't committed them until feedback and thoughts on 3.
> fix: directly import entities from metadata.ts, support top level await

- packages/test-utils/src/index.ts
- packages/test-utils/src/run.ts
- packages/test-utils/src/seed.ts
- packages/test-utils/src/toMatchEntity.ts
Historically I've not found seed functions useful, b/c I like to just run test suites to generate my boundary conditions, but :shrug: they are a thing.
> feat: Add a seed function

- packages/orm/src/newTestInstance.ts
When sinon's fake timers are installed, `global.Date` is mutated to its own `ClockDate` function, which breaks our equality check to the `field.type`, which will have captured the original `global.Date` value.
> fix: Fix factories defaulting tests when sinon is used.

- packages/orm/src/EntityFilter.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/QueryParser.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
Previously Joist supported multiple order bys, but only if they were embedded within a single object literal.
This works but is overly implicit (relying on key/insertion order) vs. just taking an actual list of order bys.
Fixes #1074
> feat: Support multiple separate order bys.

- packages/orm/src/reactiveHints.ts
- packages/tests/integration/src/EntityManager.reactiveRules.test.tsx
If we saw a hint like:
* child (no subtypes) -> parent (that is a subtype) -> something else
When we would reverse it, and try to go:
* something else -> parent (that is a different subtype) -> children
The `parent[children]` would blow up, b/c that o2m may not exist.
This is very similar to conditionally walking through polys, so we reuse the same `parent@Subtype` to infra to stop the walking before trying to access `parent[children]`.
> fix: Fix reacting to subtype-only relations.

- packages/orm/src/EntityMetadata.ts
- packages/orm/src/reactiveHints.ts
- packages/tests/integration/src/EntityManager.reactiveRules.test.tsx
- packages/tests/integration/src/entities/Critic.ts
- packages/tests/integration/src/reactiveHints.test.ts
This adds a test to reproduce the prior "walk through a different subtype that does not have the relation" error, as well as applies the fix to m2o and m2m handling as well.
There is also a related fix that runtime filtering of the type filter, i.e. `publisher@Publisher` should pass for subtypes of `Publisher` like either a `LargePublisher` or `SmallPublisher`, and previously we were only exact-matching on the type name.
> fix: Add tests for previous reactive hint fix, with more fixes.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/orm/src/EntityMetadata.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/configure.ts
- packages/tests/esm-misc/joist-config.json
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/entities/codegen/AuthorCodegen.ts
- packages/tests/integration/src/entities/codegen/CommentCodegen.ts
- packages/tests/integration/src/entities/codegen/UserCodegen.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/temporal/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/untagged-ids/src/entities/codegen/CommentCodegen.ts
- packages/tests/uuid-ids/joist-config.json
Previously filters on poly fields could not see below the immediate poly id value.
This was because each poly component has fundamentally different types.
This PR adds support by just exposing each poly component as a dedicated key in the filter, i.e.:
```ts
em.find(Comment, { parentBook: { title: "b1" } });
```
Where `Comment.parent` is a poly of `Author | Book`, and previously we could only filter on `parent: ...basic condition on the id...`.
> feat: Support filtering by poly components

- packages/codegen/src/EntityDbMetadata.ts
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/codegen/src/index.ts
- packages/graphql-codegen/src/testUtils.ts
- packages/orm/src/configure.ts
- packages/tests/integration/src/EntityManager.ctiQueries.test.ts
- packages/tests/integration/src/entities/codegen/AuthorCodegen.ts
- packages/tests/integration/src/entities/codegen/BookAdvanceCodegen.ts
- packages/tests/integration/src/entities/codegen/CommentCodegen.ts
- packages/tests/integration/src/entities/codegen/ImageCodegen.ts
Using the same trick/infra as filtering by poly components, we expose the subtypes of pointing-to-CTI m2o fields as sibling suffixes.
> feat: Allow filtering m2o by CTI subtypes.

- packages/tests/integration/src/EntityManager.queries.test.ts
This shows that `LEFT OUTER JOIN`s are being used, so that comments with just the book FK set, or just the author FK set, will match.
Fixes #1094.
> chore: Add test for poly component finds w/or.

- packages/orm/src/EntityManager.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/dataloaders/loadDataLoader.ts
- packages/orm/src/dataloaders/oneToManyDataLoader.ts
- packages/orm/src/dataloaders/oneToManyFindDataLoader.ts
- packages/orm/src/dataloaders/oneToOneDataLoader.ts
- packages/tests/integration/src/EntityManager.test.ts
The `EM.hydrate` method is a somewhat private-ish method for loading an entity from a row result set.
It has conditional behavior on what to do if, when hydrating a row, that row has already been loaded into an in-memory entity.
The safest option is to ignore the new hydrate, because it might right over WIP changes in the current EM/entity.
However, the prior default was `overwriteExisting: true`, and then we just put `overwriteExisting: false` in a bunch of places. Which was fine, except we forgot one, in the lensDataLoader.
This surfaced as a bug in production not because of the incorrect overwriteExisting behavior, but because it highlighted that the overwriteExisting behavior was really pretty slow, because it had not been optimized to use the lazy row/data serde hand-off.
This PR …
> fix: Fix lens finds going through overwriteExisting path.

- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/EntityManager.test.ts
This is just handling primitives; there is probably more work to be done in realizing that m2o values have changed, and keeping both sides of the newly-updated relation in sync.
> fix: EntityManager.hydrate should clear dirty fields.

- packages/codegen/src/config.ts
- packages/codegen/src/foreignKeyOrdering.ts
- packages/codegen/src/generateEntityCodegenFile.ts
- packages/codegen/src/index.ts
- packages/codegen/src/inheritance.ts
No code changes, just moving methods into smaller files
> chore: Break up codegen/index.ts.

- packages/orm/src/fields.ts
Line 21 is throwing this error:
```sh
ReferenceError: fail is not defined
```
Instead of the correct `Missing serde for myFieldName` error.
It looks like an import was added last week for `import { maybeRequireTemporal } from "./utils";` where there didn't used to be any imports from `./utils`, so maybe it used to be getting this for free or from the environment somehow?
> fix(fields.ts): fail not defined

- packages/codegen/src/inheritance.ts
- packages/tests/esm-misc/joist-config.json
- packages/tests/immediate-foreign-keys/joist-config.json
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/SingleTableInheritance.test.ts
- packages/tests/integration/src/entities/codegen/TaskItemCodegen.ts
- packages/tests/integration/src/entities/inserts.ts
- packages/tests/number-ids/joist-config.json
- packages/tests/schema-misc/joist-config.json
- packages/tests/temporal/joist-config.json
- packages/tests/untagged-ids/joist-config.json
- packages/tests/uuid-ids/joist-config.json
When we have base types, the normal filter only exposes the fields available on the base type/all subtypes.
However we recently allowed to subtype-specific filtering with a syntax of `<field><subtype>`, typed to the subtype filter, which then allowed using each of the subtype's fields.
We built this for CTI, but STI should have gotten it for free, except that the STI.subtypes field was not getting wired up correctly, and so it just got skipped by accident.
> fix: Add STI subtypes as per-type filters.

- packages/orm/src/BaseEntity.ts
- packages/orm/src/Entity.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/ReactionsManager.ts
- packages/orm/src/index.ts
- packages/orm/src/newTestInstance.ts
- packages/orm/src/relations/Relation.ts
- packages/test-utils/src/toMatchEntity.ts
- packages/tests/integration/src/relations/ReactiveReference.test.ts
* Enable with `setReactionLogging(true)` for global logging
* Enable with `em.setReactionLogging(true)` for per-EM logging
* Adds `Entity.toTaggedString()` which could be useful elsewhere
Another example:
> feat: Add reaction logging

- packages/orm/src/QueryParser.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
Previously Knex was helping out and defaulting these to ASC.
> fix: Prune undefined order bys.

- packages/orm/src/EntityManager.ts
- packages/orm/src/ReactionsManager.ts
- packages/tests/integration/src/relations/ReactiveReference.test.ts
We already logged the "changed --> downstream" walking, now also log what explicitly we're loading + how long it takes:
> feat: Add loading info to ReactionLogger output.

- packages/orm/src/reactiveHints.ts
- packages/orm/src/utils.ts
This was not actually a hot spot, but still good to avoid lambdas when iterating over 10k of entities.
> fix: Lightly optimize followReverseHint.

- packages/orm/src/defaults.ts
I.e.
```
config.setDefault("original", b => b);
```
> fix: Fix synchronous defaults on m2o fields.

- packages/orm/src/EntityManager.ts
- packages/orm/src/JoinRows.ts
- packages/tests/integration/src/relations/ManyToManyCollection.test.ts
When RQFs are being updated, the `em.flush` goes through multiple cycles of "flush work so far", "recalc RQF from SQL query", "re-flush anything newly changed", etc.
This iterative loop requires finer-grained tracking that our user-facing isDirtyEntity, which we'd generally already solved by via additional "flushed vs. pending" tracking.
This flushed/pending tracking was only 80% in place for m2m rows, so this PR adds the last 20%, specifically:
* Each RQF loop recalcs the latest joinRowTodos
* Calculating the joinRowTodos only looks at 'pending' m2m operations
* We fix a few bugs where internal m2m row state wasn't flipping back to pending.
> fix: Fix m2m deletes when RQFs are updated.

- packages/migration-utils/src/utils.ts
- packages/tests/integration/src/entities/Author.test.ts
This PR adds logic to improve querying many-to-many tables.
Today, when a many-to-many table is created, a composite index is created. This composite index enforces uniqueness between the two columns in the table. This index is also helpful when querying _the first column_ defined in the index. However, queries for just the second column will be inefficient.
Let's look at a concrete example. Imagine you have a many to many table linking tags and authors.
Today, the table would look like this:
```
joist=# \d authors_to_tags;
Table "public.authors_to_tags"
Column   |           Type           | Collation | Nullable |                   Default
------------+--------------------------+-----------+----------+---------------------------------------------
id         | integer                  | …
```
> feat: index all foreign keys in many to many tables

- docs/docs/advanced/full-text-search.md
- docs/docs/modeling/enum-tables.md
- packages/migration-utils/src/utils.ts
- packages/tests/integration/migrations/1580658856631_author.ts
- packages/tests/integration/src/entities/Author.test.ts
- packages/tests/number-ids/migrations/1580658856631_author.ts
- packages/tests/untagged-ids/migrations/1580658856631_author.ts
- packages/tests/uuid-ids/migrations/1580658856631_author.ts
I noticed that when you use `.addIndex` you get indexes that end with `_index`. In joist, we'd sometimes use `.addIndex`, but sometimes we'd use `b.sql` and specify `_idx` for indexes.
This PR updates all uses of `b.sql` for creating indexes to use `b.addIndex` for consistency.
NOTE: I don't feel super-strongly about this. If you don't want to make this change, no problem at all 😄
> feat: index suffix _idx -> _index

- packages/codegen/src/scanEntityFiles.ts
- packages/tests/integration/src/entities/Book.ts
Turns out it was already rewritten to do the inverted regex flow - I was looking at the inital PR which added it, not main.
- Add adds the single quote to the regex. Fixes #1202
- Changes one of the integration entity setDefault calls to use single quotes w/ prettier ignore comment - I assume this should suffice as a decent enough check.
> fix: support single quotes in scanEntityFiles

- packages/codegen/src/scanEntityFiles.ts
The two `\w`s was throwing off the code that was later hard-coded to checking only match[1] instead of match[1] or match[2].
Getting back to just one \w lets the match[1] code stay as-is.
> fix: Fix regex to have only 1 group.

- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/EntityManager.modes.test.ts
- packages/tests/integration/src/setupTestEnv.ts
Allows putting the EM into either read-only (no mutations allowed) or in-memory-writes (mutations allowed but no writes).
The in-memory-writes in particular is useful for building "oracle" functionality where you want to mutate entities to "see what would happen", but ensure the WIP data is never committed to the db, even by an errant, over-eager `em.flush`.
> feat: Add EntityManager.mode.

- packages/orm/src/drivers/buildKnexQuery.ts
- packages/orm/src/drivers/buildRawQuery.ts
- packages/tests/integration/src/QueryParser.quotes.test.ts
After renaming a entity to something abreviated to a psql keyword, I hit the following;
```
SELECT DISTINCT "to".*, to.id FROM tender_offer AS "to" LEFT OUTER JOIN other_table AS ot ON "to".id = ot.some_id WHERE ot.other_id = $1 ORDER BY "to".id ASC LIMIT $2 - syntax error at or near "to""
```
Notice the second `to` being unquoted within the select. I suspect this is due to the locations identified within the PR not using kqDot.
> fix: Missing kqDot within distinct/orderBy

- packages/codegen/src/config.ts
Updates `warnInvalidConfigEntries` to move to the next itteration if the entity within the config is not found, instead of returning early. This allows all found issues to be printed in one execution, vs needing to manually fix-run ad nasuem.
edit; thoughts on a --strict flag or something to return a non-zero exit code if any of these warnings are printed? We would find something like this very helpful for CI
> fix: continue instead of return on config warnings

- packages/orm/src/configure.ts
- packages/orm/src/defaults.ts
- packages/tests/integration/src/EntityManager.defaults.test.ts
If a single `em.flush` had both a `BaseTodo` and a `SubTodo`s, where `BaseTodo.createdBy` was set once on all `BaseTodo`s, and again for all `SubTodo`s, we'd call `.resolve()` twice on the `createdBy` deferred.
> fix: Don't double-tap the deferred on subtypes.

- packages/orm/src/newTestInstance.ts
Avoids `new[Entity]` from attempting to provide defaults for required derived enum fields.
> fix: newTestInstance to not provide default value for required derived enum columns

- packages/orm/src/defaults.ts
No semantic changes, just a missed optimization.
> fix: Add missing ??= operator.

- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/SingleTableInheritance.test.ts
I've yet to be able to reproduce why this was failing in graphql-service, but working in joist. However, these changes do get it working in graphql-service.
> fix: Sync derived fields on STI types

- packages/orm/src/configure.ts
- packages/tests/integration/src/Inheritance.test.ts
- packages/tests/integration/src/entities/Publisher.ts
- packages/tests/integration/src/entities/SmallPublisher.ts
Fixes base and sub type metadata access within the `afterMetadata` lifecycle hook by calling `hookUpBaseTypeAndSubTypes` before `fireAfterMetadata` within `configureMetadata`.
> fix: Call hookUpBaseTypeAndSubTypes before fireAfterMetadatas

- packages/orm/src/defaults.ts
- packages/orm/src/newTestInstance.ts
- packages/tests/integration/src/EntityManager.defaults.test.ts
- packages/tests/integration/src/EntityManager.factories.test.ts
- packages/tests/integration/src/FieldLogging.test.ts
- packages/tests/integration/src/entities/Book.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
Because factory entities are DeepNew/deeply loaded, it's very likely that what would, in production, usually be an async `setDefault` call (requiring a Promise to load data from the db) can, in a test, actually be done synchronously (by assuming the test instance has the data already in memory).
This PR leans into that assumption, and uses a cute `async () => {}.constructor` check to guess at whether a `setDefault` lambda is synchronous or not.
It's not foolproof but should work.
> feat: Update factories to set defaults immediately.

- packages/orm/src/BaseEntity.ts
- packages/orm/src/Entity.ts
The new `setDeepPartial` method was causing our internal tsc build to OOME; my guess was maybe because of tsc type-checking that the `...Codegen.setDeepPartial`s sufficiently implement the base type `Entity.setDeepPartial` / `BaseEntity.setDeepPartial` methods.
Particularly given that the base `setDeepPartial` used various "probably not cheap" things like `OptsOf<Entity>` or `OptsOf<this>`.
This PR simplies the base types to just `set...(opts: unknown)` with the rationale that anyone doing metaprogramming against Entity or BaseEntity will likely be doing `any`-ish type stuff anyway, and for anyone else going through concrete entities, they'll get the `Codegen.set...` methods to enforce type-safety.
> fix: Simplify base setPartial/setDeepPartial types.

- packages/orm/src/reactiveHints.ts
- packages/orm/src/relations/ReactiveReference.ts
- packages/orm/src/relations/hasAsyncProperty.ts
The `N extends undefined | never` was not inferring, so use separate function overloads, which gets the right `never` overload to be inferred first, if possible/appropriate.
> fix: Fix inference for required hasReactiveReference.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/codegen/src/inheritance.ts
- packages/orm/src/dataloaders/oneToManyDataLoader.ts
- packages/orm/src/relations/OneToManyCollection.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/ClassTableInheritance.test.ts
- packages/tests/integration/src/entities/codegen/SmallPublisherGroupCodegen.ts
- packages/tests/integration/src/entities/codegen/metadata.ts
Similar to a SmallPublisher.group: SmallPublisherGroup m2o specialization, allow a SmallPublisherGroup.publishers: SmallPublishers specialization.
Note that these may go hand-in-hand, and be set on both sides of a relation, but not necessarily, i.e. it could be valid for the SmallPublisherGroup to have any type of Publisher, until this hint was specifically added, in addition to the "SmallPublisher.group is a SmallPublisherGroup hint".
> feat: Allow o2m subtype specialization.

- packages/codegen/src/generate.ts
- packages/graphql-codegen/src/generateGraphqlSchemaFiles.test.ts
- packages/graphql-codegen/src/generateGraphqlSchemaFiles.ts
- packages/graphql-codegen/src/graphqlUtils.ts
- packages/graphql-codegen/src/index.ts
- packages/graphql-codegen/src/testUtils.ts
- packages/utils/src/index.ts
Fixes #1282.
Also changes the plugin api to `run(Config, DbMeta)` which is better, more "parameter/context object" API than passing the entities, enums, etc. all as separate params.
> feat: Type GraphQL subtyped m2os as Like.

- packages/orm/src/EntityManager.ts
- packages/orm/src/Todo.ts
- packages/orm/src/configure.ts
- packages/orm/src/defaults.ts
- packages/tests/integration/src/FieldLogging.test.ts
A single `config.setDefault("type", { identity: "type" })` might actually have separate dependency resolutions, if subtypes are in place.
See the example in the code, but a regular RPV.type default doesn't have a dependency, b/c the hint's RP.type is not an async default.
But a POV.type, which knows its identity is a PV, it turns out that PV.type does have an async default.
We were already doing some separate of "set defaults on base type separately from defaults on sub types", but weren't letting them have different dependency resolutions.
> fix: Fix specialized default dependencies.

- packages/orm/src/loadLens.ts
- packages/tests/integration/src/EntityManager.lens.test.ts
Going from a nullable reference, like `Author | undefined`, to a not-nullable reference, like `Book`, would drop the `undefined` "maybe-ness" of the type.
This fixes the `Lens` mapped type to keep the `| undefined`.
> fix: Fix lens through a non-null reference.

- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/EntityManager.test.ts
If an entity was both deleted & mutated, it would get returned from findWithNewOrChanged, instead of completely filtered out.
> fix: Fix findWithNewOrChanged not filtering deleted changed items.

- packages/orm/src/EntityMetadata.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/keys.ts
- packages/orm/src/serde.ts
- packages/tests/untagged-ids/joist-config.json
- packages/tests/untagged-ids/migrations/1580658856631_author.ts
- packages/tests/untagged-ids/src/entities/BookReview.test.ts
- packages/tests/untagged-ids/src/entities/BookReview.ts
- packages/tests/untagged-ids/src/entities/codegen/AuthorCodegen.ts
- packages/tests/untagged-ids/src/entities/codegen/BookReviewCodegen.ts
- packages/tests/untagged-ids/src/entities/codegen/metadata.ts
- packages/tests/untagged-ids/src/entities/entities.ts
- packages/tests/untagged-ids/src/entities/factories/newBookReview.ts
Users would still need to bring-their-own IdAssigner interface, but in theory it will work, as we support/don't blow up on `id` columns that are type `text`.
> feat: Unblock CUID support.

- packages/orm/src/defaults.ts
- packages/tests/integration/src/FieldLogging.test.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
If a factory invokes a default, and it returns `undefined`, we want to try the default again during `em.flush`.
> fix: Allow defaults to recalc during flush.

- packages/orm/src/defaults.ts
- packages/tests/integration/src/EntityManager.defaults.test.ts
- packages/tests/integration/src/FieldLogging.test.ts
If an explicit `await em.setDefaults(...)` invokes defaults that return `undefined`, we want to avoid setting that on the entity, so that during `em.flush`, the `setDefault` logic gets to "try again".
> fix: Allow defaults to try twice.

- packages/codegen/package.json
- packages/graphql-codegen/package.json
- packages/migration-utils/package.json
- yarn.lock
I noticed that `joist` is requesting a few specific versions, which make the dependency tree of consuming projects more complex.
Here's how I noticed it in a project:
```shell
>  yarn why prettier
├─ my-project@workspace:.
│  └─ prettier@npm:3.4.2 (via npm:^3.4.2)
|
├─ @types/prettier@npm:3.0.0
│  └─ prettier@npm:3.4.2 (via npm:*)
│
└─ joist-graphql-codegen@npm:1.215.3
└─ prettier@npm:3.4.1 (via npm:3.4.1)
```
Joist is requiring _exactly_ prettier version 3.4.1, which makes this tree more complex. We should allow `^3.4.1` so the package manager can more effectively dedupe.
> fix: loosen dependencies

- packages/orm/src/BaseEntity.ts
- packages/tests/integration/src/Entity.test.ts
- packages/tests/integration/src/entities/Author.test.ts
Previously the `1` part of a new entity's `Author#1` toString() was "the index within all authors in the EntityManager".
This was fine, but I had been using the `#1` as a quick easy to count the number of entities created during an em.flush, i.e. seeing `Author#5` === "the 5th newly created Author".
But previously the `#5` could have been "the 1st newly created Author, after we loaded 4 other existing Authors".
This PR changes the `#` numbers to only increment/indexOf against other also-newly-created entities.
> fix: Fix toString to sequentially assign new entities.

- packages/orm/src/index.ts
- packages/orm/src/temporalMappers.ts
This lets downstream applications use them in their own code, to use when reading the now-raw-strings date values off the wire of custom SQL queries.
I.e. previously node-pg converted all of DATE/TIMESTAMP/TIMESTAMPTZ to JS Dates, but now Joist proactively tells the node-pg driver to leave them as strings, and maps them in its serde layer.
We could potentially add a configuration option that pushes the Temporal-ization back into the node-pg driver, so that users would immediately see the Temporal types, even from their custom SQL queries, but it seemed cute (admittedly maybe too cute) to let Joist's serde layer do this, b/c it can convert the dates lazily, only upon access.
But it's likely subjective whether this perf benefit is worth the decreased DX of custom queries getting back …
> feat: Export temporal CustomSerde mappers.

- packages/orm/src/AliasAssigner.ts
- packages/orm/src/Aliases.ts
- packages/orm/src/EntityFilter.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/QueryVisitor.ts
- packages/orm/src/dataloaders/findByUniqueDataLoader.ts
- packages/orm/src/dataloaders/findCountDataLoader.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/drivers/Driver.ts
- packages/orm/src/drivers/buildKnexQuery.ts
- packages/orm/src/drivers/buildRawQuery.ts
- packages/orm/src/drivers/buildUtils.ts
- packages/orm/src/plugins/PreloadPlugin.ts
- packages/plugins/join-preloading/src/JsonAggregatePreloader.ts
- packages/tests/integration/src/EntityManager.find.batch.test.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/QueryParser.quotes.test.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
- packages/tests/integration/src/setupTestEnv.ts
This is a fairly massive rewrite of the SQL that `em.find` issues for o2m queries.
Specifically when filtering on children, i.e. `em.find(Author, { books: ...conditions... })`, previously we would `LEFT OUTER JOIN` into whatever `N` child rows, and then use `SELECT DISTINCT` against the `a.id`, to avoid having a singular `authors` row returned multiple times (i.e. once per book):
```sql
SELECT DISTINCT a.* FROM authors as A
LEFT OUTER JOIN books b ON b.author_id = a.id
LEFT OUTER JOIN comments c ON c.author_id = a.id
```
This `SELECT DISTINCT` worked, but created performance issues if multiple large child collections were queried, i.e. something like `em.find(Author, { books: ...conditions..., comments: ...conditions... })`.
With this query, if a single Author has `N` books and `M` …
> feat: Remove DISTINCT usage in em.find queries

- docs/docs/logging/field-logging.md
- packages/orm/src/EntityManager.ts
```ts
em.setFieldLogging("Author.firstName.lastName");
em.setFieldLogging(["Author.firstName", "Book.title!"]);
```
Fixes #1275
> feat: Add easier overloads to EM.setFieldLogging.

- packages/utils/package.json
The one sad non-link in Dependabot! 😅
> chore: add repo link to joist-utils package.json

- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/EntityManager.test.ts
`findWithNewOrChanged(Author, { publisher: null })` did a `publisher_id IS NULL` in the db, but wasn't handled by `sameEntity`.
> fix: Fix findWithNewOrChanged on null relations.

- packages/orm/src/EntityManager.ts
Minor adjustment to the javadoc from `Author#firstName` => `Author.firstName`
> chore: Correct setFieldLogging javadoc to use correct delimiter

- packages/test-utils/src/index.ts
- packages/test-utils/src/toMatchEntity.ts
- packages/tests/bun/bunfig.toml
- packages/tests/bun/src/entities/Author.test.ts
- packages/tests/bun/src/setupDbTests.ts
Pretty surprised, but bun's clone of the Jest/expect `utils.matcherHint` is basically what `toMatchObject` does, and is much more straight-forward to call, so we get pretty diffs (same as Jest, but easier to achieve/less hacky in bun):
> feat: Basic toMatchEntity working in Bun.

- packages/orm/src/EntityManager.ts
- packages/tests/integration/src/EntityManager.test.ts
This fixes a breaking change in the last refactoring, that removed `Knex` from the `EntityManager` interface.
This restores the "pass a not-yet-issued query" but by using a `PromiseLike` instead of the `Knex` type directly.
> fix: Restore loadFromQuery w/PromiseLike rows.

- docs/docs/getting-started/configuration.md
- packages/codegen/package.json
- packages/codegen/src/config.ts
- packages/codegen/src/generate.ts
- packages/drivers/bun-pg/src/BunPgDriver.ts
- packages/graphql-codegen/package.json
- packages/orm/src/EntityManager.ts
- packages/orm/src/EntityMetadata.ts
- packages/orm/src/createOrUpdatePartial.ts
- packages/tests/bun-sql-pg/src/entities/codegen/metadata.ts
- packages/tests/bun/src/entities/codegen/metadata.ts
- packages/tests/esm-misc/src/entities/codegen/metadata.ts
- packages/tests/immediate-foreign-keys/src/entities/codegen/metadata.ts
- packages/tests/integration/joist-config.json
- packages/tests/integration/src/EntityManager.txns.test.ts
- packages/tests/integration/src/entities/codegen/metadata.ts
- packages/tests/integration/src/testEm.ts
- packages/tests/number-ids/src/entities/codegen/metadata.ts
- packages/tests/schema-misc/src/entities/codegen/metadata.ts
- packages/tests/temporal/src/entities/codegen/metadata.ts
- packages/tests/untagged-ids/src/entities/codegen/metadata.ts
- packages/tests/uuid-ids/src/entities/codegen/metadata.ts
- yarn.lock
Setting `transactionType: "Knex.Transaction@knex"` in joist-config.json will restore the `txn: Knex.Transaction` typing in methods like `em.transaction` / `afterTransaction` / etc.
> fix: Add transactionType config to get txn types back.

- packages/orm/src/EntityManager.ts
- packages/orm/src/ReactionsManager.ts
- packages/orm/src/reactiveHints.ts
Currently we don't support reacting to ReactiveReferences, because they don't have an in-memory "other side" of their relation.
I.e. with a ReactiveReference of Author.favoriteBook, a rule like:
```ts
authorConfig.addRule({ favoriteBook: "title", firstName: {} }, a => {
return a.firstName === a.favoriteBook.get.title ? "bad" : undefined;
});
```
When `Book.title` changes, our reaction logic would try to:
"Look for author's that I'm the favorite book of", which would be the relation `book.favoritedByAuthors` and "follow" that relation to say "tell those authors to rerun their validation rule".
This reactivity leverages the "other side" relation, i.e. `book.favoritedByAuthors`, however we currently do not codegen the "other side" collection for ReactiveReferences because it's difficult to …
> fix: Better error message for unsupported reactivity.

- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/dataloaders/findOrCreateDataLoader.ts
- packages/tests/integration/src/EntityManager.test.ts
findOrCreate fundamentally assumes it can "eval the `where` clause against all in-memory entities", so that we don't dup against a just-created entity.
Currently we don't assume that entity has non-primitive relations loaded into memory, and even if we did `populate` those into memory, the concept of "this entity is unique based on (...)" really is meant to match "basically what a database constraint" can eval, i.e. just fields/columns directly owned on the entity.
Fixes #1375
> fix: findOrCreate should reject collections

- packages/orm/src/EntityManager.ts
- packages/orm/src/loadLens.ts
- packages/orm/src/relations/ManyToManyCollection.ts
- packages/orm/src/relations/ManyToManyLargeCollection.ts
- packages/orm/src/relations/OneToManyCollection.ts
- packages/orm/src/relations/OneToManyLargeCollection.ts
- packages/orm/src/relations/OneToOneReference.ts
- packages/orm/src/relations/RecursiveCollection.ts
Any time a batched operation fails, it will fail in "the other context" / the dataloader's setTimeout-d callback, where the error.stack doesn't know about the caller-who-is-blocking's context/stack.
And so it's error.stack will not include the caller's own stack:
```
error: SELECT a.* FROM authors AS a WHERE a.id = $1 ORDER BY a.id ASC LIMIT $2 - invalid input syntax for type integer: "0.6931471805599453"
at Object.raw (/home/stephen/other/joist-orm/node_modules/knex/lib/knex-builder/make-knex.js:116:30)
at Function.value (/home/stephen/other/joist-orm/node_modules/knex/lib/knex-builder/make-knex.js:92:29)
at PostgresDriver.executeQuery (/home/stephen/other/joist-orm/packages/orm/src/drivers/PostgresDriver.ts:69:8)
at PostgresDriver.executeFind …
```
> fix: Improve post-dataloader stack traces.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/orm/src/JoinRows.ts
- packages/orm/src/changes.ts
- packages/tests/integration/src/entities/codegen/AuthorCodegen.ts
- packages/tests/integration/src/entities/codegen/BookCodegen.ts
- packages/tests/integration/src/entities/codegen/BookReviewCodegen.ts
- packages/tests/integration/src/entities/codegen/CommentCodegen.ts
- packages/tests/integration/src/entities/codegen/PublisherCodegen.ts
- packages/tests/integration/src/entities/codegen/TagCodegen.ts
- packages/tests/integration/src/entities/codegen/TaskCodegen.ts
- packages/tests/integration/src/entities/codegen/TaskOldCodegen.ts
- packages/tests/integration/src/entities/codegen/UserCodegen.ts
- packages/tests/integration/src/relations/ManyToManyCollection.test.ts
```ts
// When we remove a1 from t1
t1.authors.remove(a1);
// And add a1 to t2
t2.authors.add(a1);
// Then a1.changed shows both added/removed
expect(await a1.changes.tags.changed).toMatchEntity([t1, t2]);
// And t1/t2.changed reflect show the same change
expect(await t1.changes.authors.changed).toMatchEntity([a1]);
expect(await t2.changes.authors.changed).toMatchEntity([a1]);
```
Fixes #1386
> feat: Add m2m added/removed/changed to changes.

- packages/orm/src/changes.ts
- packages/tests/integration/src/relations/ManyToManyCollection.test.ts
This matches the recent o2m.changes methods, which are leaning into the "technically this can be sync right now, so why now" better DX.
> fix: Remove promises from m2m.changes methods.

- packages/orm/src/BaseEntity.ts
- packages/orm/src/defaults.ts
- packages/tests/integration/src/FieldLogging.test.ts
If an entity has a synchronous `config.setDefault` that creates a new entity, then this will create a new entity from within the call stack of another entity's constructor.  This will change `currentlyInstantiatingEntity` to the newest entity and any code in the original entity's constructor that executes after, eg custom relations without `properties-transformer`, will pull in the wrong entity leading to unpredictably behavior.
> fix: reset currentlyInstantiatingEntity inside setSyncDefaults

- packages/codegen/src/config.ts
- packages/codegen/src/utils.ts
- Fixes #1398
- Add optional `"includeSchema"` option to `joist-config.json`
- Taking an array of schema names
> feat: add includeSchema option to config, with default of public

- docs/src/content/docs/logging/field-logging.md
- packages/orm/src/BaseEntity.ts
- packages/orm/src/config.ts
- packages/orm/src/logging/FieldLogger.ts
- packages/tests/integration/src/FieldLogging.test.ts
- `em.setFieldLogging("Author.constructor")` will log each time an author is `em.create`-d
- `em.setFieldLogging("Author.constructor!")` will breakpoint each time an author is `em.create`-d
With the existing breakpoint support, this also supports debugging when entities are created.
Currently this specifically creating of new entities, and not hydration of existing entities into memory.
> feat: Add support for logging instantiation.

- packages/codegen/src/generateEntityCodegenFile.ts
- packages/orm/src/changes.ts
- packages/tests/integration/src/ClassTableInheritance.test.ts
- packages/tests/integration/src/SingleTableInheritance.test.ts
- packages/tests/integration/src/entities/codegen/LargePublisherCodegen.ts
- packages/tests/integration/src/entities/codegen/SmallPublisherCodegen.ts
- packages/tests/integration/src/entities/codegen/TaskNewCodegen.ts
- packages/tests/integration/src/entities/codegen/TaskOldCodegen.ts
Very odd, these errors were ghost-like in that they only showed up in Webstorm, but not `tsc`, even though they were valid compile errors (i.e. `SmallPublisher` not being a valid subtype of `Publisher` due to the `set(opts)` parameter not being contravariant).
I was able to fully reproduce (i.e. get `tsc` to fail on them) both errors by extracting/recreating a few simplified scenarios added to the `ClassTableInheritance.test.ts`.
The two fixes are:
1. Keeping `SmallPublisherOpts.group: PublisherGroup` instead of specializing it to `SmallPublisherGroup`
The reason is that code like:
```
updatePublisher(p: Publisher): void {
p.set({ group: regularPublisherGroup });
}
```
Needs to accept `SmallPublisher`s, and not break its type contract, which making `sp.set({ group: ... })` typed as a …
> fix: Fix subtype specialization type errors

- packages/orm/src/config.ts
- packages/tests/integration/src/entities/Author.test.ts
- packages/tests/integration/src/entities/Author.ts
Allow hooks like `beforeCreate`/`beforeUpdate`/etc to receive a returnable function, so it can save the `async/await` when doing something else rather than setting a default value.
Before:
```js
config.beforeCreate(async (author) => {
await maybePublishAuthorBooks(author);
});
```
After:
```js
config.beforeCreate((author) => maybePublishAuthorBooks(author));
```
> fix: allow HookFn return value

- packages/orm/src/EntityManager.ts
- packages/orm/src/config.test.ts
- packages/orm/src/config.ts
- packages/orm/src/logging/FieldLogger.ts
- packages/tests/integration/src/FieldLogging.test.ts
Not that it'd be enabled in production, but if locally you run:
```
em.setFieldLogging("TakeoffLineItemVersion");
```
In some backend code, it will route through the `ctx.logger.debug`, instead of the default `process.stdout`, which will get batched/aligned better with the rest of the log output.
> feat: Log to ctx.logger.debug if available

- packages/drivers/bun-pg/src/BunPgDriver.ts
- packages/orm/src/EntityManager.ts
- packages/orm/src/drivers/Driver.ts
- packages/orm/src/drivers/PostgresDriver.ts
- packages/tests/integration/src/testDrivers.ts
- packages/tests/integration/src/testEm.ts
Given EntityManagers are request-level, they can end up be instantiated all over the place.
But the Driver is typically process-level, so instantiated just once during context boot.
Given this, the driver is a more natural "global behavior on/off" choke point -- and the preload setting is very driver-based anyway, i.e. currently uses JSON aggregate/pg-specific details.
> feat: Allow setting preloadPlugin at the driver level.

- packages/orm/src/drivers/buildRawQuery.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
Instead of doing `SELECT DISTINCT ...all the columns, including preload rollups...`, we use `SELECT DISTINCT ON (primary key) ...all the columns, ...` which excludes the rollups from the `DISTINCT` calc.
This is arguably a good idea anyway, disclaimer that  we want `DISTINCT`s to go away entirely.
Fixes #1468
> fix: Fix preloading when filtering by o2m joins.

- packages/knex/src/buildKnexQuery.ts
- packages/orm/src/ConditionBuilder.ts
- packages/orm/src/QueryParser.pruning.ts
- packages/orm/src/QueryParser.ts
- packages/orm/src/QueryVisitor.ts
- packages/orm/src/dataloaders/findCountDataLoader.ts
- packages/orm/src/dataloaders/findDataLoader.ts
- packages/orm/src/drivers/buildRawQuery.ts
- packages/orm/src/drivers/buildUtils.ts
- packages/orm/src/index.ts
- packages/orm/src/plugins/PreloadPlugin.ts
- packages/plugins/join-preloading/src/JsonAggregatePreloader.ts
- packages/tests/integration/src/EntityManager.find.batch.test.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
This backports a cleaner `em.find` batching from the `fix-joins-again` branch, and lands it by itself w/o the CTE-based/non-DISTINCT joins.
> feat: Use cross join for em.find batching.

- packages/orm/src/serde.ts
- packages/tests/temporal/package.json
- packages/tests/temporal/src/entities/temporal.plainDate.test.ts
- yarn.lock
`mapFromJsonAgg` doesn't need to decode to the domain-value, b/c we lazy decode result-value to domain-value all the time, so having `mapFromJsonAgg` do it on the way into `row` meant we'd do it twice.
Added docs.
> fix: Fix preloading with temporal

- packages/orm/src/QueryParser.ts
- packages/orm/src/dataloaders/populateDataLoader.ts
- packages/tests/integration/src/EntityManager.populate.test.ts
The base type join needs to come first, i.e. this works:
```sql
SELECT sp.id, _a._ as _a
FROM small_publishers AS sp
LEFT OUTER JOIN publishers AS sp_b0 ON sp.id = sp_b0.id
CROSS JOIN LATERAL (SELECT json_agg(...) as _ FROM authors AS _a WHERE _a.id = sp_b0.spotlight_author_id) AS _a
WHERE sp.id = ANY($1);
```
But this does not:
```sql
SELECT sp.id, _a._ as _a
FROM small_publishers AS sp
CROSS JOIN LATERAL (SELECT json_agg(...) as _ FROM authors AS _a WHERE _a.id = sp_b0.spotlight_author_id) AS _a
LEFT OUTER JOIN publishers AS sp_b0 ON sp.id = sp_b0.id
WHERE sp.id = ANY($1);
```
Because the sp_b0.spotlight_author_id column isn't available to the CROSS JOIN LATERAL.
> fix: Fix preloading m2os from the base type.

- .idea/joist-orm.iml
- packages/orm/src/EntityManager.ts
- packages/orm/src/IndexManager.ts
- packages/orm/src/fields.ts
- packages/tests/integration/src/EntityManager.factories.test.ts
- packages/tests/integration/src/EntityManager.findWithNewOrChanged.test.ts
- packages/tests/integration/src/IndexManager.test.ts
- packages/tests/integration/src/relations/ReactiveReference.test.ts
I didn't really expect to "need in-memory indexing" for Joist, but we've had several lifecycle hooks (like `beforeFlush`) get invoked for ~1,000+ entities (in a large, bulk upload/bulk update), which if the lifecycle does an innocent-looking `em.findWithNewOrChanged`, would turn into a `O(N^2)`.
I.e. 1,000 entities all doing a linear-scan for "did any of the other 1,000 entities `entityMatches(...my find argument...)`".
We can avoid the `O(N^2)` by reverse indexing the field values of the 1,000 entities, and then doing map/set lookups for `entityMatches` instead of a linear scan. 
This test:
```ts
const em = newEntityManager();
const n = 5_000;
// Create entities to trigger indexing
zeroTo(n).forEach((i) => em.create(Author, { firstName: `Author${i}` }));
// Test that searches are now …
```
> feat: Use indexes for findWithNewOrChanged

- packages/orm/src/EntityManager.ts
- packages/orm/src/JoinRows.ts
- packages/orm/src/dataloaders/manyToManyDataLoader.ts
- packages/orm/src/drivers/PostgresDriver.ts
Before, loading ~10k m2ms would become slow b/c of a `this.rows.find` linear scan that was invoked in a loop:
After:
> feat: Add indexing to m2m JoinRows.

- packages/orm/src/dataloaders/findDataLoader.ts
- packages/tests/integration/src/EntityManager.queries.test.ts
When creating CTE values, we'd been casting them to the default type, which was the columns jsonb type.
But we need them treated as jsonpath types, so that the @@/@? operators work.
> fix: Fix batching of jsonpath operators.

- packages/orm/src/getProperties.ts
- packages/tests/integration/src/Entity.test.ts
- packages/tests/integration/src/entities/Author.test.ts
- packages/tests/integration/src/entities/Author.ts
Due to the changes in #1586, `this` inside a property initialization callback (such as for `hasAsyncProp`) no longer refers to the instance being instantiated, but rather to the fake instance generated by `getProperties`.  This can result in unpredictable behavior and is tricky to debug, as often the error won't reveal itself immediately upon access.  This PR addresses this by making any access of a property on `this` inside one of these callbacks immediately throw an error.  We accomplish this by deleting the "own" properties on the fake instance and then installing a proxy as its prototype, which allows us to respond to any access by immediately failing.
> chore: disallow `this` in property callbacks

- packages/orm/src/ReactionsManager.ts
- packages/orm/src/config.ts
- packages/orm/src/configure.ts
- packages/tests/integration/src/EntityManager.reactions.test.ts
- packages/tests/integration/src/EntityManager.reactiveRules.test.tsx
- packages/tests/integration/src/entities/Author.ts
adds an optional `runOnce` flag to `addReaction` that causes it to operate more like a traditional hook, eg only once per flush call regardless of additional changes
> feat: add runOnce option to addReaction

- packages/orm/src/EntityManager.ts
- packages/orm/src/ReactionsManager.ts
- packages/tests/integration/src/relations/ReactiveQueryField.test.ts
This PR addresses the following scenario:
1. the initial run of a reactable during flush fails due to a missing id
2. when the reactable runs again during `recalcReactablesPendingAssignedIds` it mutates a field that has its own reactive dependencies
3. the mutated field is on an entity that is already in `alreadyRanHooks` 
4. `findPendingFlushEntities` puts nothing in `pendingHooks`
5. the dependencies of the mutated field are never re-run
> fix: assign ids and recalc reactables pending ids within recalcPendingReactables

- packages/orm/src/EntityManager.ts
- packages/orm/src/IndexManager.ts
- packages/tests/integration/src/EntityManager.findWithNewOrChanged.test.ts
Specifically when indexing kicks in, above 500 entities of the given type.
> fix: Fix findWithNewOrChanged on empty where clauses.

- packages/orm/src/EntityManager.ts
This fixes toString/toTaggedString accidentally returning #0.
> fix: Register entities earlier in create.
